### ISSUE TITLE
No visible feedback when git push requires user input

### ISSUE THREAD

**Issue by hanoii** [divmain/GitSavvy#90] opened 2015-03-13 22:59 UTC
Today I pushed to a host, and because I removed .ssh/known_host, git push was probably asking me to confirm the SSH signature of the remote host, which happens normally on a terminal. 

I saw no feedback on sublime about this and I really thought that git push was failing for some other reason external to me. It might be good to know if a commend failed or is requesting user action for any reason.

**Comment by divmain** [comment] 2015-03-13 23:29
This one is complicated.

As it is, the user will be shown the `stderr` output if a `git` command fails.  However, if it hangs (waiting for user input, for example), the plugin will continue waiting for the process to end.  Usually, `git` knows it is not in a terminal and fails hard where it would normally prompt for input.  So I'm surprised that isn't the case here.

I'll do some investigation to see if there'd be a good way about this.  A simple timeout won't work for the simple reason that sometimes an initial `git fetch` will take a really long time.  I'll come back to this once I've had some time to think through the best way to resolve.

**Comment by yyyc514** [comment] 2015-03-20 02:52
Could we use more manual file IO here against Popen's stdout/stderr vs using `communicate` and then check for the most common error conditions that would cause a hang (ssh keys, etc)?  That way you could abort instead of hanging forever.

**Comment by divmain** [comment] 2015-03-20 07:12
The problem is that this then becomes an asynchronous operation, whereas right now it is synchronous (and simple).  Definitely doable, but will involve a significant effort, I think.

**Comment by yyyc514** [comment] 2015-03-26 12:07
Wouldn't have to be to detect a lot of errors... you could still be totally sync, just paying attention to the output.  I might play with this.

**Comment by yyyc514** [comment] 2015-07-04 12:36
What's the quickest way to hack my setup so it throws an input prompt?

**Comment by divmain** [comment] 2015-07-16 08:40
@yyyc514, the most straightforward way I can think of is to setup a remote that will requires SSH, and encrypt your SSH key.  Git would then prompt you for a password.  That should be completely reproducible, methinks.

The problem here, though, is that the subprocess will never terminate - it will keep on waiting for user input that never comes.  So you won't have a chance to inspect the standard output of the subprocess at the end.  I've considered adding a timeout of some sort, but honestly Git can take awhile, especially on large repos.  So that seems like a very risky choice, to say the least.

**Comment by divmain** [comment] 2015-09-20 08:02
Closing this, as there doesn't appear to be a good option under Sublime Text 3.  A fix would involve either 1) adding significant complexity to the codebase using async communication everywhere, or 2) timing out Git operations which seems dubious at best.

**Closed by divmain** 2015-09-20 08:02 UTC
Labels: ux
