### ISSUE TITLE
play nice with vintageous

### ISSUE THREAD

**Issue by leemhenson** [divmain/GitSavvy#65] opened 2015-03-10 10:59 UTC
as a [vintageous](https://github.com/guillermooo/Vintageous) user
when I open ```git: status``` and see that it acts like a normal vintageous-aware document
I do not want any commands (e.g. ```[d]```) to be acted upon unless I am in insert mode

**Comment by divmain** [comment] 2015-03-10 18:01
@leemhenson - I just pushed a change to `master` that should resolve this issue.  When you get a chance, can you [pull down the master branch](https://github.com/divmain/GitSavvy/blob/master/README.md#less-simple) and see if the issue is resolved?  If so, I'll include the change in the next release.

**Comment by leemhenson** [comment] 2015-03-11 08:33
Ok, I've installed it from master and it looks like it is now completely disabling Vintageous on the status view....

**Comment by leemhenson** [comment] 2015-03-11 08:46
Oh I think I miscommunicated my wish. I don't want Vintageous disabled, I just want GitSavvy to only respond to keypresses if I am in Vintageous' insert mode. I should be able to use Vintageous (and other plugins, e.g. EasyMotion) to move my cursor to the appropriate filename, switch to Insert Mode and then stage, commit etc.

**Comment by leemhenson** [comment] 2015-03-11 08:47
If it's any help, I got the same thing implemented on SublimeGit too: https://github.com/SublimeGit/SublimeGit/issues/125

**Comment by divmain** [comment] 2015-03-11 20:53
Can you explain a bit more about how this works in SublimeGit?  I'm happy to address this, but the more information you can give me, the sooner I'll get to it?

Also, how would you feel about a key-combo that:
- disables GitSavvy's status view key-bindings
- removes `__vi_external_disable` from the view (enabling Vintageous key-bindings)

On second press, it would do the opposite.  There could be an option in GitSavvy settings that would invert this behavior.

**Comment by leemhenson** [comment] 2015-03-12 10:43
In SublimeGit I use a setting:

```"git_status_disable_vintageous": false``` 

and that's all I need to do. Vintageous operates normally and when I switch to insert mode, all of Sublime Git's keybindings are activated. Drop out of insert mode, and the SG keybindings are deactivated.

**Comment by divmain** [comment] 2015-03-12 17:19
@leemhenson, I'll take a whack at this.  From your description, Vintageous must either set properties on the view when not in insert mode, or it provides a hook of some sort for when the transition occurs.

**Comment by divmain** [comment] 2015-03-13 04:40
@guillermooo, hope you don't mind my asking: can you recommend a strategy for accomplishing this?  Essentially, key-bindings for GitSavvy should only be in effect when Vintageous enters insert mode.  I took a cursory look through the Vintageous codebase and didn't see any obvious view settings that I could check for.

**Comment by jipumarino** [comment] 2015-06-08 17:34
Hi @divmain. This is already working for the status view, could you please add the diff views too?

**Comment by divmain** [comment] 2015-06-23 22:15
Hi @jipumarino, I don't have much bandwidth for GitSavvy at the moment.  Addressing this issue will be something of an investment for me, since I'm not a vintageous user.  So for now, this is a low-priority issue.  I'm very open to PRs if you'd like to take a whack at it, or if you could do some investigation on the vintageous side to elucidate what needs to change, either would be very helpful.

**Comment by jipumarino** [comment] 2015-06-24 15:38
;) Thank you, I'll give it a shot and let you know how it goes.

**Comment by divmain** [comment] 2015-10-07 09:31
Since I don't have much to go on, closing this issue.  Feel free to re-open if and when there's more information for how to interact with vintageous.

**Closed by divmain** 2015-10-07 09:31 UTC
Labels: enhancement, ux
