### ISSUE TITLE
Can't see full description of blame options in menu

### ISSUE THREAD

**Issue by kiddick** [divmain/GitSavvy#592] opened 2017-01-18 09:45 UTC
![image](https://cloud.githubusercontent.com/assets/9250239/22058958/56a947d2-dd84-11e6-8b5f-db303385a740.png)

Source:
https://github.com/divmain/GitSavvy/blob/2d41dec240e07434502206407373a9425a3c3631/core/commands/blame.py#L22

**Comment by stoivo** [comment] 2017-01-18 13:01
This is probably caused by your theme. Could you less up which theme you are using as well as sublime version?

**Comment by kiddick** [comment] 2017-01-18 13:15
Sublime Text 3 (build 3126)
Theme: https://github.com/equinusocio/material-theme Material Theme

**Comment by stoivo** [comment] 2017-01-23 07:35
I tested I can not reproduce.
This theme was several themes, which theme do you 

I would like to see this setting.
```
  "color_scheme": "Packages/Material Theme/schemes/Material-Theme.tmTheme",
```

Also there are many settings, have you sent any of these?

**Comment by kiddick** [comment] 2017-01-23 10:56
```
"color_scheme": "Packages/Color Scheme - Default/Monokai.tmTheme",
	"indent_guide_options":
	[
		"draw_normal",
		"draw_active"
	],
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"material_theme_accent_cyan": true,
	"material_theme_appbar_charcoal": true,
	"material_theme_bullet_tree_indicator": true,
	"material_theme_compact_panel": true,
	"material_theme_compact_sidebar": true,
	"material_theme_contrast_mode": true,
	"material_theme_panel_separator": true,
	"material_theme_small_statusbar": true,
	"material_theme_small_tab": true,
	"material_theme_tabs_autowidth": true,
	"material_theme_tree_headings": true,
	"overlay_scroll_bars": "enabled",
```

**Comment by stoivo** [comment] 2017-01-23 13:01
I open an issue for material-theme I think it should be solved there.

**Comment by equinusocio** [comment] 2017-01-23 13:20
https://github.com/equinusocio/material-theme/issues/1070

**Comment by stoivo** [comment] 2017-03-02 21:15
@equinusocio, this is a issue in you theme. I will close this issue. Please reopen if you feel like we can do anything.

**Closed by stoivo** 2017-03-02 21:15 UTC

**Comment by equinusocio** [comment] 2017-03-03 08:03
This is a sublime related issue that doesn't recalculate the correct padding :(

**Comment by kiddick** [comment] 2017-09-13 13:58
Finally fixed with https://www.sublimetext.com/blog/articles/sublime-text-3-point-0

**Comment by stoivo** [comment] 2017-09-14 21:02
@equinusocio  🎉

**Comment by equinusocio** [comment] 2017-09-15 04:56
I hope so.
