### ISSUE TITLE
Custom command: missing part of output

### ISSUE THREAD

**Issue by aziz** [divmain/GitSavvy#442] opened 2016-06-26 18:59 UTC
I'm trying to add some custom commands from the `git-extras` package. 
The one I've problem with is `git summary`.

Here is my custom command definition: 
```json
[
  {
    "caption": "git: summary",
    "command": "gs_custom",
    "args": {
        "output_to_panel": true,
        "args": ["summary"],
    }
  }
]
```

The desired output is 

```
 project  : GitSavvy
 repo age : 1 year, 5 months
 active   : 207 days
 commits  : 872
 files    : 163
 authors  : 
   631	Dale Bustad         72.4%
    52	Simon               6.0%
    36	Adrian L Lange      4.1%
    20	Pavel Savchenko     2.3%
    18	David Devlin        2.1%
    17	Randy Lai           1.9%
    16	Allen Bargi         1.8%
    14	Josh Goebel         1.6%
    13	gwenzek             1.5%
    13	Nicolás Santángelo  1.5%
     5	Laas Toom           0.6%
     5	Petr Marek          0.6%
     4	Eldar Abusalimov    0.5%
     4	Dave Nicolson       0.5%
     3	Steve Bennett       0.3%
     3	marcinruszkiewicz   0.3%
     2	Ethan Bustad        0.2%
     1	David Nicolson      0.1%
     1	Oliver Hoffmann     0.1%
     1	David Mohl          0.1%
     1	old9                0.1%
     1	Philipp Klose       0.1%
     1	Shadab Zafar        0.1%
     1	Craig Campbell      0.1%
     1	Sindri Guðmundsson  0.1%
     1	Brett Dixon         0.1%
     1	laggingreflex       0.1%
     1	Harel               0.1%
     1	Felix               0.1%
     1	Jeff Langston       0.1%
     1	John Burnett        0.1%
     1	MJ                  0.1%
     1	Max Mykhailenko     0.1%
```

what I get in output panel is

```
 project  : GitSavvy
 repo age : 1 year, 5 months
 active   : 207 days
 commits  : 872
 files    : 163
 authors  : 
```

The whole authors list is missing. Any clue?

**Comment by stoivo** [comment] 2016-06-26 20:10
I remember that I had a similar issue that @divmain helped me solve.

I will see if I can remember what it was.

**Comment by stoivo** [comment] 2016-06-26 21:04
Simon @stoivo Feb 11 22:01
Hey, I am having some stage issue.
I am making a dropdown with all committers to select from when you want to log by author. To implement this i found the command `git shortlog -sne`, this log all committers. Here comes the stage thing:
```print(self.git("shortlog", "-sne").strip())```
This prints an empty string? What is going on here.
I the terminal
```
$ /usr/bin/git shortlog -sne
   568  Dale Bustad <dale@divmain.com>
    36  Adrian L Lange <mail@p3lim.net>
    24  Simon <simon.toivo@telhaug.no>
    14  Josh Goebel <dreamer3@gmail.com>
    13  Nicolás Santángelo <santangelonicolas@gmail.com>
    11  Pavel Savchenko <pavel@modlinltd.com>
    10  David Devlin <dave.devlin@gmail.com>
     7  David Devlin <d.devlin@keelvar.com>
     5  Laas Toom <laas.toom@gmail.com>
     5  Pavel Savchenko <asfaltboy@gmail.com>
     3  marcinruszkiewicz <marcin.ruszkiewicz@polcode.net>
     3  Steve Bennett <stevage@gmail.com>
     2  Ethan Bustad <ethan.bustad@liferay.com>
     1  old9 <qi.jiahui@gmail.com>
     1  Brett Dixon <theiviaxx@users.noreply.github.com>
     1  David Mohl <me@dave.cx>
     1  Harel <harelstern@users.noreply.github.com>
     1  Jeff Langston <jeffl@rmatv.com>
     1  John Burnett <johnburnett@johnburnett.com>
     1  Max Mykhailenko <max.mykhailenko@gmail.com>
     1  Oliver Hoffmann <oliverh855@gmail.com>
     1  Philipp Klose <me@thehippo.de>
     1  Randy Lai <randy.cs.lai@gmail.com>
     1  Simon <simon.toivo@gmail.com>
```

Dale Bustad @divmain Feb 12 02:37
@stoivo that is very strange! (also, a great idea)

Dale Bustad @divmain Feb 12 02:43
I'm taking a look now

Dale Bustad @divmain Feb 12 02:50
Ah, from the docs:

    If no revisions are passed on the command line and either standard
    input is not a terminal or there is no current branch, git shortlog
    will output a summary of the log read from standard input, without
    reference to the current repository.

@stoivo, use `print(self.git("shortlog", "-sne", "@"))`
or `print(self.git("shortlog", "-sne", "HEAD"))`

Simon @stoivo Feb 12 10:44
Do you have the link to docs I can get

Dale Bustad @divmain Feb 12 10:44
just google for git shortlog manpage
that's typically the first thing I do what I'm using an unfamiliar git command

Simon @stoivo Feb 12 15:56
thx,

Simon @stoivo Feb 12 18:12
I will go for self.git("shortlog", "-sne", "HEAD")

Dale Bustad @divmain Feb 12 20:10
👍 


This is our conversation when I had a similar problem.

**Comment by stoivo** [comment] 2016-06-26 21:17
Right now I think it might be correct to fix it in git-extras. Since it is all written in shell is should not be to hard to check.
I think the issue is in this line 
https://github.com/tj/git-extras/blob/1f374d1ea9f7e595f127b805184b8288c056c1e5/bin/git-summary#L52

**Comment by divmain** [comment] 2016-06-28 07:59
I'm impressed you spotted that @stoivo!  I would have had to hunt around for the same answer again.  @aziz, I'm going to go ahead and close this ticket since this is an unavoidable constraint of `git shortlog`.  If you can think of ways to augment GitSavvy for workarounds, especially in a generic way, please feel free to re-open!

**Closed by divmain** 2016-06-28 07:59 UTC
