### ISSUE TITLE
cherry-pick: 'GsCherryPickCommand' object has no attribute 'view'

### ISSUE THREAD

**Issue by braver** [divmain/GitSavvy#941] opened 2018-05-18 09:43 UTC
- Sublime Text version number 3176
- Git version number 2.15.1 (Apple Git-101)
- OS type and version macOS 10.13.4
- Console error output 

```
Traceback (most recent call last):
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/ui_mixins/quick_panel.py", line 526, in <lambda>
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/ui_mixins/quick_panel.py", line 530, in on_selection_async
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/commands/log.py", line 32, in <lambda>
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/commands/log.py", line 37, in on_done
  File "/Users/koenlageveen/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package/core/commands/cherry_pick.py", line 17, in do_action
AttributeError: 'GsCherryPickCommand' object has no attribute 'view'
```

- A description of the problem: When a cherry-pick is successful it seems to try and log something, which fails.

[debug.txt](https://github.com/divmain/GitSavvy/files/2016309/debug.txt)

**Comment by braver** [comment] 2018-05-19 07:52
I get this whenever I cherry pick a commit via the gitsavvy command palette UI. I could try and see if it’s a more specific bug, but just cherry pick something should do it.

**Comment by asfaltboy** [comment] 2018-05-19 08:16
Ah ok, you're right it's easily reproduced! I missed that the cherry-pick completes ok (!), and then the traceback appears in console. Here's the full traceback on `develop` branch:

```python
Traceback (most recent call last):
  File "/Users/pavel.savchenko/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/ui_mixins/quick_panel.py", line 532, in <lambda>
    sublime.set_timeout_async(lambda: self.on_selection_async(commit), 10)
  File "/Users/pavel.savchenko/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/ui_mixins/quick_panel.py", line 536, in on_selection_async
    self.on_done(commit)
  File "/Users/pavel.savchenko/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/log.py", line 34, in <lambda>
    lambda commit: self.on_done(commit, file_path=file_path, **kwargs),
  File "/Users/pavel.savchenko/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/log.py", line 45, in on_done
    self.do_action(commit, **kwargs)
  File "/Users/pavel.savchenko/Library/Application Support/Sublime Text 3/Packages/GitSavvy/core/commands/cherry_pick.py", line 17, in do_action
    self.view.window().status_message("Commit %s cherry-picked successfully." % commit_hash)
AttributeError: 'GsCherryPickCommand' object has no attribute 'view'
reloading /Users/pavel.savchenko/Library/Application Support/Sublime Text 3/Packages/GitSavvy/tests/test_core_commands/__init__.py
```

**Comment by stoivo** [comment] 2018-05-22 09:37
close since merged into dev

**Closed by stoivo** 2018-05-22 09:37 UTC
Labels: bug, in progress
