### ISSUE TITLE
Improve cursor position on status view

### ISSUE THREAD

**Issue by max-mykhailenko** [divmain/GitSavvy#159] opened 2015-03-31 07:19 UTC
When status view opens need to set cursor position at line with first file.
When file was staged by pressing `s`, cursor position must be changed to next unstaged file

**Comment by divmain** [comment] 2015-03-31 18:11
I'll consider this.

Generally speaking, I like to stick to the principle of least surprise.  Since this is a text editor, people don't usually expect their cursor to move around unless you tell it to.  So the behavior now is for GitSavvy to try to keep the cursor at the same row and column after every command.

It might be worth adding key-bindings for `.` and `,` to go to the next and previous section, respectively.  That might be a good shortcut for someone like you who doesn't want to have to move the cursor around too much, while not sacrificing expected behavior.

**Comment by yyyc514** [comment] 2015-03-31 19:33
What about shift-s, alt-s, etc. for stage + next?

**Comment by max-mykhailenko** [comment] 2015-04-01 05:46
After using SublimeGit about year I can tell that move cursor position it's normal. Status view it's more Dashboard than simple text file, it's interface.

Examples:
- open status – press `s` several times (1-3) – `c` commit
- open status – set cursor to block title (Unstaged for example) – press `s` (all unstaged files add to staged) – commit

But maybe I just should use `C`...

**Comment by alextegelid** [comment] 2015-04-01 06:17
I agree that the status dashboard (tags and branch too) feels more like an application view than just a text editor. 



I suggest the cursor stays in it's current position relative to the list of files rather than the text editors rows.

**Comment by divmain** [comment] 2015-04-02 00:32
If we go the route of automatic cursor positioning after specific actions, we will need to develop some hard and fast rules about what the cursor does, and when.  It could get complex.

For example, take the staged files section:

If the cursor is positioned over the third file in staged section, and the user un-stages that file, the new third-file in the staged section should be highlighted after the action.  If, however, the action taken results in the last file in the section being removed, the cursor should go to the line above in order to stay in the staged section.  Also, if the action results in the highlighted section being removed, where should the cursor go?  To the section at the top, no matter what?  To different places, depending on which section disappeared?

Then add multiple cursors.  And add the fact that all cursors are regions that could span multiple lines.  And add the fact that some users might want the cursor to behave differently, and would want auto-positioning to be optional.

If everybody is for this, we can definitely give it a try.  But I think it may be difficult to implement well and costly to maintain.

I've been considering an alternative that might get everyone a lot closer to what they want.  We could have keybindings to take users to the start of the sections.  So @max-mykhailenko's workflow only has to adjust slightly - 1) open the status view, 2) _press the key to position the cursor in the unstaged file section_, 3) press `s` several times, and 4) commit.

**Comment by max-mykhailenko** [comment] 2015-04-02 06:32
@divmain really so complex. As developer I don't like complex solutions and now not recommend resolve this issue.
I will try to design more intuitive and simple solution.

**Comment by divmain** [comment] 2015-04-02 06:42
Alright @max-mykhailenko. This is a good discussion to have, so thanks for bringing it up. I may also be failing to see a straightforward approach - if you think of something, please do let me know. I do agree that the current behavior could be improved upon...

**Comment by alextegelid** [comment] 2015-04-02 06:42
@divmain I didn't realize until now that I can use multiple cursors for staging multiple files. That's a bonus, thanks!

**Comment by noon-ehos** [comment] 2015-04-02 08:02
I also used sublimeGit about year. And I can say - it really good Idea to set cursor to first unstaged file on open status dashboard. And its not your troubles "What to do with cursor/cursors on any user action?". Just set it once at open status dashboard to first unstaged file. Always when I want to stage something (not all) I must move cursor to block with unstaged files.

**Comment by divmain** [comment] 2015-04-02 18:24
Sure, I don't see why not.  For now, we'll leave cursor behavior as-is, except that the cursor will be initially positioned on the first file of the unstaged section (when the dashboard initially loads).

**Comment by max-mykhailenko** [comment] 2015-04-03 06:49
This will work only if staged files will be under unstaged

**Comment by divmain** [comment] 2015-04-04 08:22
That's very true... I'll play around with moving it and see if that's a natural change to make.  If not, we'll have to come up with something else.

**Comment by divmain** [comment] 2015-09-20 07:54
I'm going to consider this done with 82bb849, 00ba8fc5108abffbd9169116d047eac1b5d2f9b8, and f3da14ddee8b658c009ed920405da44ebc542c2c.  Cursor should be positioned on first unstaged file when a new status dashboard is created, and navigation between files is unencumbered with `.` and `,` key-bindings.

**Closed by divmain** 2015-09-20 07:54 UTC
Labels: investigate, ux
