### ISSUE TITLE
Can't commit: "Window does not exist"

### ISSUE THREAD

**Issue by franciscolourenco** [divmain/GitSavvy#772] opened 2017-09-04 08:33 UTC
```
Traceback (most recent call last):
  File "core.git_command in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 103, in git
  File "core.git_command in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 297, in repo_path
RuntimeError: Window does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.commands.commit in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 142, in <lambda>
  File "core.commands.commit in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 162, in run_async
  File "core.git_command in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 106, in git
  File "core.exceptions in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 7, in __init__
TypeError: GitSavvyError does not take keyword arguments
```

**Comment by stoivo** [comment] 2017-09-04 10:25
Can you give the steps to reproduce?

**Comment by aristidesfl** [comment] 2017-09-04 10:37
@stoivo I don't know them. It seems to happen randomly.

**Comment by aristidesfl** [comment] 2017-09-04 12:06
```
>>> import shutil, sys, sublime; print("which git:", shutil.which("git")); print("os:", sys.platform); print("sublime version:", sublime.version()); print("GitSavvy git:", sublime.load_settings("GitSavvy.sublime-settings").get("git_path"))
which git: /usr/bin/git
os: darwin
sublime version: 3133
GitSavvy git: 
```

**Comment by astephensen** [comment] 2017-09-06 03:54
I'm also having this issue. It's very random, maybe 1 in 10 commits won't actually be committed. If I recommit it again it usually works fine.
```
which git: /usr/local/bin/git
os: darwin
sublime version: 3142
GitSavvy git: 
```

**Comment by stoivo** [comment] 2017-09-06 05:55
Are there some specific files that you have this issue with. Files with spaces? files with emoji in?

**Comment by astephensen** [comment] 2017-09-06 06:09
I don't think the files were that strange but I'll definitely take more notice now. I found it weird that committing the files the second time around works fine, even without making any other changes.

I had initially suspected something wrong with my git because GitSavvy has been working fine for the past ~year I've been using it. I think this issue has only really appeared within the last few weeks for me.

I'll try turning on logging to see if that reveals anything.

**Comment by aristidesfl** [comment] 2017-09-07 13:33
Recorded log:
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 797, in run_
    return self.run()
  File "common.commands.debug in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 57, in run
  File "common.util.debug in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 36, in get_log
  File "./python3.3/json/__init__.py", line 240, in dumps
  File "./python3.3/json/encoder.py", line 193, in encode
  File "./python3.3/json/encoder.py", line 411, in _iterencode
  File "./python3.3/json/encoder.py", line 312, in _iterencode_list
  File "./python3.3/json/encoder.py", line 388, in _iterencode_dict
  File "./python3.3/json/encoder.py", line 422, in _iterencode
  File "./python3.3/json/encoder.py", line 173, in default
TypeError: b'//\n// Buttons\n// --------------------------------------------------\n$button-border-radius: 2px;\n$button-border-width: 2px;\n$button-height: $base-unit * 3;\n// Base styles\n// --------------------------------------------------\n.button {\n    font-weight: 600;\n    display: inline-block;\n    padding: 0 $base-unit;\n    margin-bottom: 0; // For input.button\n    height: $button-height;\n    line-height: $button-height - ($button-border-width * 2);\n    min-width: 180px;\n    text-align: center;\n    touch-action: manipulation;\n    cursor: pointer;\n    background-color: transparent;\n    background-image: none; // Reset unusual Firefox-on-Android default style; see https://github.com/necolas/normalize.css/issues/214\n    border: $button-border-width solid transparent;\n    border-radius: $button-border-radius;\n    white-space: nowrap;\n    @include user-select(none);\n    &,\n    &:active,\n    &.active {\n        &:focus,\n        &.focus {\n            @include tab-focus;\n        }\n    }\n    &:hover,\n    &:focus,\n    &.focus {\n        text-decoration: none;\n    }\n    &:active,\n    &.active {\n        outline: 0;\n        background-image: none;\n    }\n    &:focus,\n    &:focus:active {\n        outline-color: $outline-color;\n    }\n}\n\n.button-unstyle {\n    @include button-unstyle;\n}\n\na.button {\n    &.disabled,\n    fieldset[disabled] & {\n        pointer-events: none; // Future-proof disabling of clicks on `<a>` elements\n    }\n}\n\n.button-default {\n    color: $accent-color;\n    border-color: $accent-color;\n    &:hover {\n        background-color: rgba($accent-color, 0.1);\n    }\n    &.selected {\n        color: $primary-color;\n        border-color: $primary-color;\n        pointer-events: none;\n    }\n    &.disabled {\n        color: $text40;\n        border-color: $text40;\n        pointer-events: none;\n    }\n}\n\n.button-primary {\n    color: $white;\n    // border-color: $accent-color;\n    background-color: $accent-color;\n    &:focus,\n    &:focus:active {\n        box-shadow: 0 2px 1px 0 rgba(82, 97, 147, 0.72);\n    }\n    &:hover {\n        box-shadow: 0 3px 5px 0 rgba(82, 97, 147, 0.72);\n    }\n    &:hover,\n    &:focus {\n        color: $white;\n        border-color: transparent;\n        background-color: $accent-color-hover;\n    }\n    box-shadow: 0 2px 3px 0 rgba(82, 97, 147, 0.72);\n    &.disabled {\n        background-color: $text40;\n        pointer-events: none;\n    }\n}\n\n.button-inverse {\n    color: $white;\n    border-color: $white;\n}\n.button-default.button-inverse {\n    &:hover {\n        color: $white;\n        background-color: rgba($white, 0.2);\n    }\n}\n\n.button-search-tag:hover {\n    opacity: 0.8;\n    color: $white;\n}\n\n\n.button-with-icon-add.search-tag {@include button-icon("/assets/images/icons/white/add.svg");}\n.button-with-icon-add.button-default {@include button-icon("/assets/images/icons/secondary/add.svg");}\n.button-with-icon-add.button-default.button-inverse {@include button-icon("/assets/images/icons/white/add.svg");}\n.button-with-icon-arrow-right.button-default.button-inverse {@include button-icon("/assets/images/icons/white/arrow_right.svg");}\n.button-with-icon-check.button-primary {@include button-icon("/assets/images/icons/white/check.svg");}\n.button-with-icon-search.button-primary {@include button-icon("/assets/images/icons/white/search.svg");}\n.button-with-icon-add.button-default {@include button-icon("/assets/images/icons/secondary/add.svg");}\n.button-with-icon-exit.button-default {@include button-icon("/assets/images/icons/secondary/exit.svg");}\n.button-with-icon-delete.button-default {@include button-icon("/assets/images/icons/secondary/delete.svg");}\n.button-with-icon-edit.button-default {@include button-icon("/assets/images/icons/secondary/edit.svg");}\n.button-with-icon-share.button-default {@include button-icon("/assets/images/icons/secondary/share.svg");}\n.button-with-icon-lock.left.button-primary {@include button-icon("/assets/images/icons/white/lock.svg", "left");}\n.button-with-icon-lock.left.button-default {@include button-icon("/assets/images/icons/secondary/lock.svg", "left");}\n\n.button-save {\n    width: 24px;\n    height: 24px;\n    background: url(/assets/images/icons/secondary/save.svg) center no-repeat;\n    background-size: contain;\n    display: inline-block;\n    vertical-align: middle;\n    &:hover {\n        opacity: 0.8;\n    }\n}\n\n.button-search-results {\n    width: 20px;\n    height: 20px;\n    vertical-align: middle;\n}\n.button-search-results + .button-search-results {\n    margin-left: 8px;\n}\n\n.button-delete {\n    background: url(/assets/images/icons/gray/delete.svg);\n}\n.button-comment {\n    background: url(/assets/images/icons/gray/comment.svg);\n}\n.hover-highlight:hover .button-delete {\n    background: url(/assets/images/icons/secondary/delete.svg);\n}\n.button-delete::after { // preload icon\n content: url(/assets/images/icons/secondary/delete.svg);\n display: none;\n}\n.hover-highlight:hover .button-comment {\n    background: url(/assets/images/icons/secondary/comment.svg);\n}\n.button-comment::after { // preload icon\n content: url(/assets/images/icons/secondary/comment.svg);\n display: none;\n}\n\n\n\n\n// Block button\n// --------------------------------------------------\n.button-block {\n    display: block;\n    width: 100%;\n}\n\n// Vertically space out multiple block buttons\n.button-block + .button-block {\n    margin-top: 5px;\n}\n\n// Specificity overrides\ninput[type="submit"],\ninput[type="reset"],\ninput[type="button"] {\n    &.button-block {\n        width: 100%;\n    }\n}\n\n// Button Group\n// --------------------------------------------------\n.button-group {\n    @include clearfix();\n    display: inline-block;\n    position: relative;\n    vertical-align: middle;\n    >.button + .button {\n        border-left-width: 0;\n    }\n    >.button {\n        border-radius: 0;\n        float: left;\n        box-shadow: none;\n        &:active,\n        &:focus {\n            box-shadow: none;\n        }\n    }\n    >.button:first-child() {\n        border-bottom-left-radius: 100px;\n        border-top-left-radius: 100px;\n    }\n    >.button:last-child() {\n        border-bottom-right-radius: 100px;\n        border-top-right-radius: 100px;\n    }\n}\n\n.button-group.flex-wrap {\n    > .button {\n        margin: 2px;\n        border-radius: 0;\n        border-width: 2px;\n    }\n}\n\n// Buttons which are 180px wide but shrink to fit the screen,\n// until its content can\'t be displayed. Then they wrap.\n// Doesn\'t support\n.flex-buttons {\n    display: flex;\n    flex-wrap: wrap;\n    margin: round( - $base-unit / 2);\n    .button {\n        min-width: auto;\n        flex-basis: 180px;\n        margin: round($base-unit / 2);\n    }\n}\n' is not JSON serializable
```

**Comment by stoivo** [comment] 2017-09-07 20:08
Hi @aristidesfl, that bug you have open will be fixed and released next couple of days. https://github.com/divmain/GitSavvy/pull/773. That bug does not have anything to do with committing. Though, Thanks for submitting.

It would be very cool if you can record a new log when #773 is merged. I will post a comment here when that's done.

**Comment by asfaltboy** [comment] 2017-09-08 06:58
Hi @aristidesfl , what @stoivo meant is that the issue in your last comment above, a regression in debug log, is fixed in #773. We have merged the fix and released a hotfix version 2.16.3, it should be available in Package Control soon

**Comment by yeled** [comment] 2017-09-18 11:12
I'm having this (reproducible) on latest.

```
>>> import shutil, sys, sublime; print("which git:", shutil.which("git")); print("os:", sys.platform); print("sublime version:", sublime.version()); print("GitSavvy git:", sublime.load_settings("GitSavvy.sublime-settings").get("git_path"))
which git: /usr/local/bin/git
os: darwin
sublime version: 3143
GitSavvy git: 
```

```
[
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.03145289421081543, 
    "stdout": "M  ansible/playbooks/tasks/build.yml\u0000?? actual adva.graffle\u0000?? actual adva/\u0000?? actual_adva.dot\u0000?? actual_adva.png\u0000?? actual_adva_tidied_up.graffle\u0000?? actual_adva_tidied_up.png\u0000?? ansible/lab/Vagrantfile_vbox\u0000?? ansible/lab/temp/\u0000?? ansible/roles/base/templates/junos/policies.j2\u0000?? documented_adva.dot\u0000?? documented_adva.png\u0000?? isis.db.json\u0000?? labs/jnpr_building/\u0000?? lldp.dot\u0000?? lldp.map\u0000?? m10m11.dot\u0000?? m10m11.graffle\u0000?? m10m11.png\u0000?? map.png\u0000?? map.svg\u0000?? node_modules/\u0000?? package-lock.json\u0000?? portAuto\u0000?? script/lsp_bw.sh\u0000?? sdc42adva.dot\u0000", 
    "command": [
      "status", 
      "--porcelain", 
      "-z"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.02797698974609375, 
    "stdout": "## master...origin/master\nM  ansible/playbooks/tasks/build.yml\n?? actual adva.graffle\n?? actual adva/\n?? actual_adva.dot\n?? actual_adva.png\n?? actual_adva_tidied_up.graffle\n?? actual_adva_tidied_up.png\n?? ansible/lab/Vagrantfile_vbox\n?? ansible/lab/temp/\n?? ansible/roles/base/templates/junos/policies.j2\n?? documented_adva.dot\n?? documented_adva.png\n?? isis.db.json\n?? labs/jnpr_building/\n?? lldp.dot\n?? lldp.map\n?? m10m11.dot\n?? m10m11.graffle\n?? m10m11.png\n?? map.png\n?? map.svg\n?? node_modules/\n?? package-lock.json\n?? portAuto\n?? script/lsp_bw.sh\n?? sdc42adva.dot\n", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.014045000076293945, 
    "stdout": "15dd724e print \".\" on action success. Allows easier human reading of the success/failure of a particular playbook", 
    "command": [
      "log", 
      "-n 1", 
      "--pretty=format:%h %s", 
      "--abbrev-commit"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.11022806167602539, 
    "stdout": "stash@{0}: WIP on dedupe_1509: c5b2f741 move these switches to the next/missing /31 which deduplicates from `tsw[12]-cp1ae1`\nstash@{1}: WIP on master: 8586656e fix a typo\nstash@{2}: WIP on master: dc9495d0 import SDC42 ip ranges\nstash@{3}: WIP on master: 579f0573 Merge pull request #1474 from github/oops_missed_a_couple\nstash@{4}: WIP on offboarding_micahcroff: 6e67a98d Some accounts I found with git-grep after a `rake pull` on all devices\nstash@{5}: WIP on master: 9e5524e9 Merge pull request #1469 from github/ipam\nstash@{6}: WIP on low-fruit-cleanup: e4f9dc8c Fixed typo on vlan300 IP.\n", 
    "command": [
      "stash", 
      "list"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.010574817657470703, 
    "stdout": "diff --git ansible/playbooks/tasks/build.yml ansible/playbooks/tasks/build.yml\nindex 5b1418ce..b5c9625a 100644\n--- ansible/playbooks/tasks/build.yml\n+++ ansible/playbooks/tasks/build.yml\n@@ -11,7 +11,7 @@\n     file: path=../../tmp/compiled/{{inventory_hostname}} state=directory\n \n - name: Build common config\n-  hosts: all\n+  hosts: all:!lab\n   gather_facts: no\n   roles:\n     - base\n@@ -21,13 +21,12 @@\n   hosts:\n   - bdr*\n   - spine*\n-  - lab\n   gather_facts: no\n   roles:\n   - sampling\n \n - name: Assemble the config\n-  hosts: all\n+  hosts: all:!lab\n   gather_facts: no\n   tasks:\n   - name: Concatenate all the config into one file\n", 
    "command": [
      "diff", 
      "--no-color", 
      "--cached", 
      null
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.037882089614868164, 
    "stdout": "M  ansible/playbooks/tasks/build.yml\u0000?? actual adva.graffle\u0000?? actual adva/\u0000?? actual_adva.dot\u0000?? actual_adva.png\u0000?? actual_adva_tidied_up.graffle\u0000?? actual_adva_tidied_up.png\u0000?? ansible/lab/Vagrantfile_vbox\u0000?? ansible/lab/temp/\u0000?? ansible/roles/base/templates/junos/policies.j2\u0000?? documented_adva.dot\u0000?? documented_adva.png\u0000?? isis.db.json\u0000?? labs/jnpr_building/\u0000?? lldp.dot\u0000?? lldp.map\u0000?? m10m11.dot\u0000?? m10m11.graffle\u0000?? m10m11.png\u0000?? map.png\u0000?? map.svg\u0000?? node_modules/\u0000?? package-lock.json\u0000?? portAuto\u0000?? script/lsp_bw.sh\u0000?? sdc42adva.dot\u0000", 
    "command": [
      "status", 
      "--porcelain", 
      "-z"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.03519105911254883, 
    "stdout": "## master...origin/master\nM  ansible/playbooks/tasks/build.yml\n?? actual adva.graffle\n?? actual adva/\n?? actual_adva.dot\n?? actual_adva.png\n?? actual_adva_tidied_up.graffle\n?? actual_adva_tidied_up.png\n?? ansible/lab/Vagrantfile_vbox\n?? ansible/lab/temp/\n?? ansible/roles/base/templates/junos/policies.j2\n?? documented_adva.dot\n?? documented_adva.png\n?? isis.db.json\n?? labs/jnpr_building/\n?? lldp.dot\n?? lldp.map\n?? m10m11.dot\n?? m10m11.graffle\n?? m10m11.png\n?? map.png\n?? map.svg\n?? node_modules/\n?? package-lock.json\n?? portAuto\n?? script/lsp_bw.sh\n?? sdc42adva.dot\n", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.01754283905029297, 
    "stdout": "15dd724e print \".\" on action success. Allows easier human reading of the success/failure of a particular playbook", 
    "command": [
      "log", 
      "-n 1", 
      "--pretty=format:%h %s", 
      "--abbrev-commit"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.14245104789733887, 
    "stdout": "stash@{0}: WIP on dedupe_1509: c5b2f741 move these switches to the next/missing /31 which deduplicates from `tsw[12]-cp1ae1`\nstash@{1}: WIP on master: 8586656e fix a typo\nstash@{2}: WIP on master: dc9495d0 import SDC42 ip ranges\nstash@{3}: WIP on master: 579f0573 Merge pull request #1474 from github/oops_missed_a_couple\nstash@{4}: WIP on offboarding_micahcroff: 6e67a98d Some accounts I found with git-grep after a `rake pull` on all devices\nstash@{5}: WIP on master: 9e5524e9 Merge pull request #1469 from github/ipam\nstash@{6}: WIP on low-fruit-cleanup: e4f9dc8c Fixed typo on vlan300 IP.\n", 
    "command": [
      "stash", 
      "list"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.1470491886138916, 
    "stdout": "M  ansible/playbooks/tasks/build.yml\u0000?? actual adva.graffle\u0000?? actual adva/\u0000?? actual_adva.dot\u0000?? actual_adva.png\u0000?? actual_adva_tidied_up.graffle\u0000?? actual_adva_tidied_up.png\u0000?? ansible/lab/Vagrantfile_vbox\u0000?? ansible/lab/temp/\u0000?? ansible/roles/base/templates/junos/policies.j2\u0000?? documented_adva.dot\u0000?? documented_adva.png\u0000?? isis.db.json\u0000?? labs/jnpr_building/\u0000?? lldp.dot\u0000?? lldp.map\u0000?? m10m11.dot\u0000?? m10m11.graffle\u0000?? m10m11.png\u0000?? map.png\u0000?? map.svg\u0000?? node_modules/\u0000?? package-lock.json\u0000?? portAuto\u0000?? script/lsp_bw.sh\u0000?? sdc42adva.dot\u0000", 
    "command": [
      "status", 
      "--porcelain", 
      "-z"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.02535414695739746, 
    "stdout": "## master...origin/master\nM  ansible/playbooks/tasks/build.yml\n?? actual adva.graffle\n?? actual adva/\n?? actual_adva.dot\n?? actual_adva.png\n?? actual_adva_tidied_up.graffle\n?? actual_adva_tidied_up.png\n?? ansible/lab/Vagrantfile_vbox\n?? ansible/lab/temp/\n?? ansible/roles/base/templates/junos/policies.j2\n?? documented_adva.dot\n?? documented_adva.png\n?? isis.db.json\n?? labs/jnpr_building/\n?? lldp.dot\n?? lldp.map\n?? m10m11.dot\n?? m10m11.graffle\n?? m10m11.png\n?? map.png\n?? map.svg\n?? node_modules/\n?? package-lock.json\n?? portAuto\n?? script/lsp_bw.sh\n?? sdc42adva.dot\n", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.011147022247314453, 
    "stdout": "15dd724e print \".\" on action success. Allows easier human reading of the success/failure of a particular playbook", 
    "command": [
      "log", 
      "-n 1", 
      "--pretty=format:%h %s", 
      "--abbrev-commit"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.08086490631103516, 
    "stdout": "stash@{0}: WIP on dedupe_1509: c5b2f741 move these switches to the next/missing /31 which deduplicates from `tsw[12]-cp1ae1`\nstash@{1}: WIP on master: 8586656e fix a typo\nstash@{2}: WIP on master: dc9495d0 import SDC42 ip ranges\nstash@{3}: WIP on master: 579f0573 Merge pull request #1474 from github/oops_missed_a_couple\nstash@{4}: WIP on offboarding_micahcroff: 6e67a98d Some accounts I found with git-grep after a `rake pull` on all devices\nstash@{5}: WIP on master: 9e5524e9 Merge pull request #1469 from github/ipam\nstash@{6}: WIP on low-fruit-cleanup: e4f9dc8c Fixed typo on vlan300 IP.\n", 
    "command": [
      "stash", 
      "list"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.023173093795776367, 
    "stdout": "M  ansible/playbooks/tasks/build.yml\u0000?? actual adva.graffle\u0000?? actual adva/\u0000?? actual_adva.dot\u0000?? actual_adva.png\u0000?? actual_adva_tidied_up.graffle\u0000?? actual_adva_tidied_up.png\u0000?? ansible/lab/Vagrantfile_vbox\u0000?? ansible/lab/temp/\u0000?? ansible/roles/base/templates/junos/policies.j2\u0000?? documented_adva.dot\u0000?? documented_adva.png\u0000?? isis.db.json\u0000?? labs/jnpr_building/\u0000?? lldp.dot\u0000?? lldp.map\u0000?? m10m11.dot\u0000?? m10m11.graffle\u0000?? m10m11.png\u0000?? map.png\u0000?? map.svg\u0000?? node_modules/\u0000?? package-lock.json\u0000?? portAuto\u0000?? script/lsp_bw.sh\u0000?? sdc42adva.dot\u0000", 
    "command": [
      "status", 
      "--porcelain", 
      "-z"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.022660017013549805, 
    "stdout": "## master...origin/master\nM  ansible/playbooks/tasks/build.yml\n?? actual adva.graffle\n?? actual adva/\n?? actual_adva.dot\n?? actual_adva.png\n?? actual_adva_tidied_up.graffle\n?? actual_adva_tidied_up.png\n?? ansible/lab/Vagrantfile_vbox\n?? ansible/lab/temp/\n?? ansible/roles/base/templates/junos/policies.j2\n?? documented_adva.dot\n?? documented_adva.png\n?? isis.db.json\n?? labs/jnpr_building/\n?? lldp.dot\n?? lldp.map\n?? m10m11.dot\n?? m10m11.graffle\n?? m10m11.png\n?? map.png\n?? map.svg\n?? node_modules/\n?? package-lock.json\n?? portAuto\n?? script/lsp_bw.sh\n?? sdc42adva.dot\n", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.008625984191894531, 
    "stdout": "15dd724e print \".\" on action success. Allows easier human reading of the success/failure of a particular playbook", 
    "command": [
      "log", 
      "-n 1", 
      "--pretty=format:%h %s", 
      "--abbrev-commit"
    ], 
    "stderr": ""
  }, 
  {
    "type": "git", 
    "stdin": null, 
    "seconds": 0.07837700843811035, 
    "stdout": "stash@{0}: WIP on dedupe_1509: c5b2f741 move these switches to the next/missing /31 which deduplicates from `tsw[12]-cp1ae1`\nstash@{1}: WIP on master: 8586656e fix a typo\nstash@{2}: WIP on master: dc9495d0 import SDC42 ip ranges\nstash@{3}: WIP on master: 579f0573 Merge pull request #1474 from github/oops_missed_a_couple\nstash@{4}: WIP on offboarding_micahcroff: 6e67a98d Some accounts I found with git-grep after a `rake pull` on all devices\nstash@{5}: WIP on master: 9e5524e9 Merge pull request #1469 from github/ipam\nstash@{6}: WIP on low-fruit-cleanup: e4f9dc8c Fixed typo on vlan300 IP.\n", 
    "command": [
      "stash", 
      "list"
    ], 
    "stderr": ""
  }
]
```

**Comment by stoivo** [comment] 2017-09-18 18:42
Hm, the log seams well. The last thing happening was opening the status. 
Do you have exact steps to reproduce? Can you reproduce on a new installation?

**Comment by yeled** [comment] 2017-09-19 09:49
Hmm I will have to find time to check on a new install.

**Comment by stoivo** [comment] 2017-09-19 10:50
> Do you have exact steps to reproduce?

Is it always failing on your current setup?
I maybe it was something to do with the repo. Is it a public repo I can checkout?

**Comment by yeled** [comment] 2017-09-19 11:50
It's.. often failing. Lately for everything, but it can come and go.

Sadly this isn't a public repo.

**Comment by mreq** [comment] 2017-11-07 10:14
This actually happens to me a lot. However, I'm not able to define a reproducible example.

Console output:

```
Traceback (most recent call last):
  File "core.git_command in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 103, in git
  File "core.git_command in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 300, in repo_path
RuntimeError: Window does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.commands.commit in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 143, in <lambda>
  File "core.commands.commit in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 163, in run_async
  File "core.git_command in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 106, in git
  File "core.exceptions in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 7, in __init__
TypeError: GitSavvyError does not take keyword arguments
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 330, in on_new
    callback.on_new(v)
  File "yaml_nav in /home/petr/.config/sublime-text-3/Installed Packages/YAML Nav.sublime-package", line 77, in on_new
TypeError: on_load() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "core.git_command in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 103, in git
  File "core.git_command in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 300, in repo_path
RuntimeError: Window does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.commands.commit in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 143, in <lambda>
  File "core.commands.commit in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 163, in run_async
  File "core.git_command in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 106, in git
  File "core.exceptions in /home/petr/.config/sublime-text-3/Installed Packages/GitSavvy.sublime-package", line 7, in __init__
TypeError: GitSavvyError does not take keyword arguments
```

**Comment by stoivo** [comment] 2017-11-07 10:19
@mreq, is it for every repository? of just a specific one?

**Comment by mreq** [comment] 2017-11-07 10:21
It happens for many repos. Not always though - one commit might be fine, another may fail (furthermore, it can fail twice and then work once). I'll clone the repo to my Packages and add some debugging code. Will be back with more info.

**Comment by mreq** [comment] 2017-11-09 16:46
Here's what I've added on top of `repo_path` method to debug - 
![image](https://user-images.githubusercontent.com/1286942/32617674-e14346ac-c575-11e7-8ff0-30147957655b.png)


Here's the log - https://www.hastebin.com/ifazabowun.txt

**Comment by stoivo** [comment] 2017-11-09 18:01
@mreq, very good report. This looks more and more like a sublime issue. 
Perhaps  this is a workaround for now?
```diff
 core/git_command.py | 12 +++++++++++-
 1 file changed, 11 insertions(+), 1 deletion(-)

diff --git a/core/git_command.py b/core/git_command.py
index 0716cff..f676c07 100755
--- a/core/git_command.py
+++ b/core/git_command.py
@@ -284,7 +284,17 @@ class GitCommand(StatusMixin,
         """
         # The below condition will be true if run from a WindowCommand and false
         # from a TextCommand.
-        view = self.window.active_view() if hasattr(self, "window") else self.view
+
+        def find_view():
+            print("working")
+            if hasattr(self, "window"):
+                try:
+                    return self.window.active_view()
+                except AttributeError:
+                    return sublime.windows()[0].active_view()
+            else:
+                return self.view
+        view = find_view()
         repo_path = view.settings().get("git_savvy.repo_path") if view else None
 
         if not repo_path or not os.path.exists(repo_path):

```

**Comment by randy3k** [comment] 2017-11-09 21:51
#804 will fix a bug so a correct exception will be thrown, but it doesn't fix the issue `Window does not exist` in the first place. AFAIK, It usually happens when a window is closed while GitSavvy is trying to update the status bar.

**Comment by randy3k** [comment] 2017-11-09 21:58
@mreq Your calls to`self.window` are throwing `AttributeError` becauses `self` is a `TextCommand`.

**Comment by mreq** [comment] 2017-11-10 09:24
I am aware of that. What @stoivo wrote might do the trick. I'll use it locally and report if the problem occurs again.

**Comment by mreq** [comment] 2017-11-10 15:01
Nope, failed again (see `2017-11-10 15:58:33.023595`) - https://www.hastebin.com/ocadivumes.txt - Is there any additional debugging code that might help you?

**Comment by stoivo** [comment] 2017-11-10 20:23
Can you add debug info for?
```
hasattr(self, "window")
```

Also, what't your platform? sublime build?

**Comment by mreq** [comment] 2017-11-13 06:32
Will do.

```
$ uname -a
Linux t470 4.10.0-38-generic #42-Ubuntu SMP Tue Oct 10 13:24:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release --all
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
```

Sublime build 3143.

**Comment by mreq** [comment] 2017-11-13 12:54
https://www.hastebin.com/feqamidavo.txt (see `2017-11-13 13:53:25.210254`)

**Comment by stoivo** [comment] 2017-11-13 21:58
Can use `dev` branch? should fix one of the exceptions

**Comment by mreq** [comment] 2017-11-13 22:05
will do and report back

**Comment by mreq** [comment] 2017-11-20 06:15
https://www.hastebin.com/wadacaramu.txt
https://www.hastebin.com/makicapeji.txt

the error stays the same:

```
Traceback (most recent call last):
  File "/home/petr/.config/sublime-text-3/Packages/GitSavvy/core/git_command.py", line 104, in git
    working_dir = self.repo_path
  File "/home/petr/.config/sublime-text-3/Packages/GitSavvy/core/git_command.py", line 327, in repo_path
    raise RuntimeError("Window does not exist.")
RuntimeError: Window does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/petr/.config/sublime-text-3/Packages/GitSavvy/core/commands/commit.py", line 143, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(commit_message=message), 0)
  File "/home/petr/.config/sublime-text-3/Packages/GitSavvy/core/commands/commit.py", line 163, in run_async
    stdin=commit_message
  File "/home/petr/.config/sublime-text-3/Packages/GitSavvy/core/git_command.py", line 107, in git
    raise GitSavvyError(e, show_panel=False)
GitSavvy.core.exceptions.GitSavvyError: Window does not exist.
```

**Comment by randy3k** [comment] 2017-11-20 06:49
The error occurs after committing a message `c+enter` but before the view is closed. 
Do you encounter any abnormalities while committing?

**Comment by mreq** [comment] 2017-11-20 07:51
I commit by closing the view (ctrl+w from insert mode). My settings:

```
{
  "dev_mode": true,
  "commit_on_close": true,
  "vintageous_friendly": true,
  "vintageous_enter_insert_mode": true
}```

outside of sublime, commit works like it should

**Comment by randy3k** [comment] 2017-11-20 16:46
👍 finally we have a clue. It seems it is related to `commit_in_close`.

**Comment by mreq** [comment] 2017-11-27 13:51
Seems like it happens more often when there's plenty of sublime windows open.

**Comment by randy3k** [comment] 2018-03-30 04:02
Let's close this now. Please report back if it happens again.

**Closed by randy3k** 2018-03-30 04:02 UTC
Labels: bug, in progress

**Comment by franciscolourenco** [comment] 2018-03-30 22:22
I still have this once in a while. Not sure it is the same console message, but sometimes the commit still fails.

**Comment by randy3k** [comment] 2018-03-30 23:07
Could you test the latest release? It should have addressed the issue.

**Comment by mreq** [comment] 2018-03-31 11:01
It was still the same for me during the week. Should I try the git/master or are the changes present in the latest package control release? Will report next week.

**Comment by randy3k** [comment] 2018-03-31 12:54
0.10.3 was released yesterday

**Comment by mreq** [comment] 2018-04-08 09:36
Hasn't occured since updating :+1: Thanks
