### ISSUE TITLE
Indistinguishable colors in inline diff

### ISSUE THREAD

**Issue by alextegelid** [divmain/GitSavvy#230] opened 2015-08-26 19:07 UTC
Colors in the inline diff have become indistinguishable. Both the added and removed line colors is gray with same-colored cyan borders. See screenshot.

I've removed the color settings from my user settings (`GitSavvy.sublime-settings`) and removed all the `.tmLanguage.cache` and `.tmTheme.cache` files recursively in the `Packages` folder. The latter in a wild attempt to fix this on my own...

http://cl.ly/image/2e0S2e3F3r0V

(Edit: add the screenshot)

**Comment by divmain** [comment] 2015-08-26 19:13
How did this come about?  This may be trivially solvable by deleting the `tmTheme` files in `Packages/User/GitSavvy`.  These themes are calculated per-file and then cached.

**Comment by alextegelid** [comment] 2015-08-26 20:00
I can't really remember what happened around the time when this started appearing. Unfortunately I have experienced this for some time but haven't reported it, thinking it was something I'd messed up myself (it still might be though).

Isn't it supposed to say something about GitSavvy in the bottom right where the current syntax is shown?

For me it says SCSS (or whatever syntax matches the file)

http://cl.ly/image/0s0R0W0n410A

**Comment by alextegelid** [comment] 2015-08-26 20:30
Sorry, forgot to report back on your solution. I tried removing the tmTheme files. But it didn't work. A new file for the scss file type was created though.

**Comment by divmain** [comment] 2015-08-26 21:55
It won't say anything about GitSavvy in the bottom right (although that's not a bad idea...).  It'll just use the same string that was in the original syntax definition.

Can you confirm which version of GitSavvy and Sublime you're using?  This seems very strange to me, and I'm trying to rack my brain for possible causes.  Can you also look for any errors in the console when you initially load an inline-diff view?

One additional thing you try is:
- install [ScopeHunter](https://github.com/facelessuser/ScopeHunter)
- open an inline-diff view
- place the cursor within one of the gray blocks of code
- copy the string that it reports, and paste that back here
- open the `tmTheme` file associated with the file you're diffing
- find the entry for the scope that you recorded above, and copy/paste that here as well

If everything matches up, i.e. the scope is set correctly and there is an entry in the theme file with the correct color, then this may be a bug with Sublime itself.

**Comment by alextegelid** [comment] 2015-08-27 07:00
GitSavvy is pulled directly from master and Sublime is in the Stable Channel, build 3083.

ScopeHunter, while cursor is standing on "size" in the screenshot below:
```
Scope:                         source.scss
                               meta.property-list.scss
                               meta.property-name.scss
                               support.type.property-name.scss
------
```

I'm a little unsure what you mean by checking the `tmTheme` file. If you mean checking `GitSavvy.active-diff-view.scss.tmTheme` (while in a scss file) I cant find any of the definitions listed above by seraching though the file.

http://cl.ly/image/211N2A2b0Q0F

**Comment by divmain** [comment] 2015-08-27 07:46
Can you upload `GitSavvy.active-diff-view.scss.tmTheme` somewhere I can take a look?  I steered you wrong with ScopeHunter - it doesn't show dynamically added scopes after all (vs ones determined by the syntax).

**Comment by alextegelid** [comment] 2015-08-27 07:49
Absolutely!
Here you go: http://pastebin.com/FW64RMW2

**Comment by nightmarebadger** [comment] 2015-08-27 11:06
Just commenting that the same thing happened to me a few days ago. Tried the following

* Reinstall GitSavvy (no difference)
* Remove .tmTheme files (no difference)
* Also remove .thTheme files (very minor difference, I could now see that the inline diffs with only a few words changed had a 'border' around those words too, kinda showing the exact difference in a line)

My version is a tiny bit different from the screenshot in the first comment, but I'm guessing that's due to a different theme (the 'grey' in my case is lighter, closer to white). 

I can check on the other computer later when I get home, the whole thing is synced over Dropbox so I'm guessing it's the same but can double check. 

Versions and OS:
* Arch Linux
* Sublime Text 3 (build 3083) - package https://aur.archlinux.org/packages/sublime-text-dev/ from the AUR
* GitSavvy v2.3.0 (installed via package manager)

**Comment by divmain** [comment] 2015-08-27 19:25
This is super strange, and possibly a Sublime bug.

The regions are obviously being added - otherwise the gray/white blocks wouldn't be appearing at all.  If added, they will have the correct scope, because that value is hard-coded.  The values from `sublime.load_settings("GitSavvy.sublime-settings").get("colors")` have been added correctly to the `tmTheme` file you uploaded, so that's not the problem.  So as long as they have the correct scope and it is themed with the active `tmTheme` file, it should appear with the correct coloration.

Alright, two more things you can try for me.

1) Open an inline diff view, and type `view.settings().get("color_scheme")` into the console.  It should list one of the generated themes; for JavaScript it should show `'Packages/User/GitSavvy/GitSavvy.active-diff-view.js.tmTheme'`.  If it doesn't paste what you see here.
2) Open a new file.  Copy the content of this GitHub comment (or just random text) into the view.  Then, in the console, enter `view.add_regions("test-region", [sublime.Region(0, 10)], "keyword.control.flow");`.  If you're using Monokai theme, the background and foreground of the first ten characters should change to something colored.

**Comment by alextegelid** [comment] 2015-08-27 19:51
Result of 1) ```'Packages/User/Color Highlighter/themes/Afterglow.tmTheme'```

This led me to try the following:
1. Disable Color Highlighter
2. Close Sublime Text
3. Delete Packages/User/GitSavvy/*.tmTheme
4. Start Sublime Text
5. **Inline diff works!**

It seems Color Highlighter takes precedence when it comes to overriding the color themes.

**Comment by alextegelid** [comment] 2015-08-27 19:53
Maybe GitSavvy gets a hold of the tmTheme file *after* Color Highlighter has already modified it?

**Comment by divmain** [comment] 2015-08-27 21:04
That's good news!  From the behavior it sounds like Color Highlighter is hijacking the theme just like GitSavvy does.  To be honest, I'm not sure if there's a deterministic way to guarantee that GitSavvy sets the theme after Color Highlighter does.

Plugin interactions are hard to know what to do with.  Do you know if Color Highlighter can be configured to ignore a particular type of view - for example, if a property is defined on the view's settings?

**Comment by stoivo** [comment] 2015-08-27 21:28
I can confirm that it is an issue with "Color Highlighter". All I did was to disable it and reload ran GitSavvy: relaod submodules and reopen the inline diff. I am really happy you all the solution/issue :)

I think we should report this a issue to ["Color Highlighter"](https://github.com/Monnoroch/ColorHighlighter), since this have been like this for top 2 weeks.

**Comment by divmain** [comment] 2015-08-27 21:35
It's a pity Sublime doesn't expose an API to dynamically augment the active color scheme.  I'm going to close this ticket for now, but feel free to re-open if something actionable turns up from your investigations with Color Highlighter.

**Closed by divmain** 2015-08-27 21:35 UTC
Labels: question

**Comment by alextegelid** [comment] 2015-08-28 07:16
You're right @stoivo, the past two weeks sounds about right.

Well the solution is simple otherwise, remove Color Highlighter. That plugin isn't nearly as useful as GitSavvy :)
Thanks for troubleshooting with me, and a special thanks to @divmain for developing GitSavvy. I'm heading over to Color Highlighters issue page.
