### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by wiselyku** [divmain/GitSavvy#952] opened 2018-06-07 08:19 UTC
I have encounter a problem. I past the error message in the following. Please help me, thank you very much.

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 45: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wisel\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/commands/push.py", line 64, in run_async
  File "C:\Users\wisel\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/commands/push.py", line 36, in do_push
  File "C:\Users\wisel\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_mixins/remotes.py", line 67, in push
  File "C:\Users\wisel\AppData\Roaming\Sublime Text 3\Installed Packages\GitSavvy.sublime-package\core/git_command.py", line 229, in git
GitSavvy.core.exceptions.GitSavvyError: Please report this error to GitSavvy:

'utf-8' codec can't decode byte 0xb6 in position 45: invalid start byte

**Comment by wiselyku** [comment] 2018-06-07 08:34
My platform is windows 10   sublime 3.1.1
I just installed the GitSavvy, and I performed git: push, then the error messages showed up.
@stoivo

**Comment by asfaltboy** [comment] 2018-09-23 10:10
@wiselyku this might be a dupe of #966 which has been closed (fallback decoding of stderr has been added), and you are now probably getting another error or issue is resolved. Please feel free to reopen the issue if there is still some unresolved issue.

**Closed by asfaltboy** 2018-09-23 10:10 UTC
Labels: not-enough-information
