### ISSUE TITLE
Hotkey commands strange behaviour

### ISSUE THREAD

**Issue by kamenjan** [divmain/GitSavvy#411] opened 2016-05-20 17:06 UTC
I've been using gitsavvy for some time now and had no issues. Few days ago I've set up a new system using El Capitan. Since then I have this strange issue when I try to use hotkey commands (e.g. [o],[s],[c] ...). Lets say I want to stage a file, I press "s" and nothing happens until I press any other key. So basically I have to "confirm" every command with any key input. I tried googling for this issue, but came up empty. Wouldn't even be that big of a deal if I was able to use STASH commands that require a combination of inputs.

I've tried reinstalling the package, but issue persists. Any ideas?

I'm using OSX El Capitan 10.11.5 and Sublime 3 Build 3114

**Comment by divmain** [comment] 2016-05-20 22:12
I have a vague recollection of this happening to me before, and I think it may have been due to a package conflict.  Have you confirmed that the strange behavior occurs with a fresh install of Sublime + GitSavvy?

**Comment by kamenjan** [comment] 2016-05-21 02:37
It was indeed a package conflict. I have removed a package named AutoSpell and issue was resolved. Thank you for fast response, cheers!

**Comment by stoivo** [comment] 2016-05-21 09:07
@divmain, should we add a note somewhere that we might have conflicts with AutoSpell?

**Comment by stoivo** [comment] 2016-05-26 20:00
I will close this issue since the issue is solved.

**Closed by stoivo** 2016-05-26 20:00 UTC
Labels: conflict with other package, investigate

**Comment by divmain** [comment] 2016-05-26 21:09
@stoivo sorry for not responding earlier.  It might be worth noting that certain plugins can interfere with GitSavvy's keybindings.  But I'm quite sure it wasn't `AutoSpell` that I ran into myself, so calling out specific packages is probably not worthwhile.
