### ISSUE TITLE
How to disable diff auto scroll

### ISSUE THREAD

**Issue by xahon** [divmain/GitSavvy#590] opened 2017-01-09 15:09 UTC
Cannot find any option to disable annoying diff autoscrolling

**Comment by stoivo** [comment] 2017-01-09 17:59
Which diff are we talking about. 
Could you add some steps to reproduce?

**Comment by asfaltboy** [comment] 2017-01-12 12:25
There's autoscroll in blame and inline-diff. The former doesn't have a toggle (AFAIK) and the latter [is settable and false by default][1]. @xahon please tell us which one you mean

[1]: https://github.com/divmain/GitSavvy/blob/e6c00ef4da1d49ea86a9f323f3541bd201838ed4/GitSavvy.sublime-settings#L58

**Comment by xahon** [comment] 2017-02-08 02:08
Try to create a large file. Like website stylesheets and open its `inline diff`. Scroll down, switch back to `STATUS` tab and switch back to `inline diff`. It'll be automatically scrolled to the top.

**Comment by divmain** [comment] 2017-03-03 09:33
@xahon this is an unfortunate constraint that likely won't be fixed.  Whenever you switch back to an inline-diff view, the contents of that view are recomputed.  This is to ensure that what you are viewing is always up-to-date.

However, because the contents of the view can change and relative cursor position is hard to get right when it does change, we chose to take the user back to the physical row (not relative to the source) that they were on last - including moving view focus.  This provides a reasonable UX for 90% of the cases, and the same logic is used to refresh the view after you've staged a hunk or line.

So when you open a view, scroll down, and leave the view, and come back, this is what happens: GitSavvy refreshes the view, sees that your _cursor_ is still on the first line, and moves focus back up to the top.  If you want focus to remain in a different part of the file, move your cursor there before leaving the view.  That's the best we can do for now, I hope that's workable for you.

**Closed by divmain** 2017-03-03 09:33 UTC
Labels: not-enough-information

**Comment by asfaltboy** [comment] 2017-03-03 14:20
@divmain nice tip, we should probably add the scroll to cursor feature in documentation if it's not there already.
