### ISSUE TITLE
Endless loop: "GitSavvy was unable to parse Git output as UTF-8"

### ISSUE THREAD

**Issue by deathaxe** [divmain/GitSavvy#594] opened 2017-01-22 18:31 UTC
GitSavvy still suffers from the endless loop, if it fails to parse git output as UTF-8. This issue is already descriped in #300. By pressing the message dialog's 'cancel' button a panel with the following message is opened, but the dialog box reapears as soon as the open DIFF view is activated again. There is no chance to close it at all. I need to kill Sublime Text and delete the recently open *.sublime-workspace file. Otherwise the DIFF view is restored and the endless loop starts again on next execution of Sublime Text.

panel text
```
'utf-8' codec can't decode byte 0xfc in position 139: invalid start byte
```

You must not expect utf-8 as encoding of any output as it doesn't need to be true for `git show` command especially if git is configured to store files in a certain encoding other then utf-8.

I can't say who is responsible but I use git for Windows 2.11.0 and GitExtensions 2.49 with default settings to do most of my work with versioning. One of them sets git's file encoding to operating system default value, which is Windows-1252 in my case.

We could discuss whether it is a good idea to store files with an enconding different from utf-8 or not but infact git allows it, so everyone needs to support it.

I am just starting to use git tools like GitSavvy directly from Sublime Text to hopefully replace external tools some day. 

## Steps to reproduce

1. Configure git to store files as Windows-1252 encoding as it is done automatically with Git for Windows on. (`i18n.filesencoding=Windows-1252`)
2. Create a repository and commit a file with none ascii characters like (äöß)
3. Modify the file in worktree
4. Call git: status
5. Select a modified file
6. press `l`  key to run inline diff
7. You are in endless loop

## System Information

- Sublime Text 3126
- GitSavvy 2.13.0 or commit e6c00ef4da1d49ea86a9f323f3541bd201838ed4
- Windows 10 x64 de-DE

**Comment by stoivo** [comment] 2017-01-22 18:37
Thank you very much for a good reproduction steps. I have had the same issue myself but never found the case of it. I will test the steps later today.

**Comment by stoivo** [comment] 2017-01-23 20:29
I have been testing yesterday and today. I have tested on Mac OSX and on Windows 10 with default installation of git from https://git-scm.com/. 

I have been setting that setting with  `git config i18n.filesencoding Windows-1252` on the repo I have tested with. It still work like it should. Is possible if you can create a repo so I can pull it down and reproduce? I think that would help us a lot.

**Comment by deathaxe** [comment] 2017-01-31 20:59
Created a repository with Windows-1252 codepage set

https://github.com/deathaxe/gitsavvy-debug.git

I created a file containing äöß, saved it with Windows-1252 encoding, committed and pushed it to the branch.

I can reproduce the issue with this repository.

1. Open the file
2. modify some chars  (keep äöß)
3. call git status
4. press `l` for inline diff

Good luck!

**Comment by hanoii** [comment] 2017-02-16 17:17
This just happened to me again, and many times, it was when diffing again. Instead of a workspace file I had to remove the buffers from `Session.sublime_session` on the sublime support dir.

Useful info: http://stackoverflow.com/questions/11744365/removing-projects-in-sublime-text-2-and-3

**Comment by stoivo** [comment] 2017-02-20 22:45
Hello, I want to tell you both than I am working on it. I think I would need to sepen couple on evenings looking at this. 

I will comment some of by progress here. 
This one one of the diffs I have been looking at to night. 

```
b'
diff --git a/43d38c4090dedfbef81efa5d6e9ac2d63eafdf59 b/8a8e0f7f9177a0f40d6d6bcc03056320f2ac0fb7
index 43d38c4..8a8e0f7 100644
--- a/43d38c4090dedfbef81efa5d6e9ac2d63eafdf59
+++ b/8a8e0f7f9177a0f40d6d6bcc03056320f2ac0fb7
@@ -1 +1 @@
-Das ist \xf6ffentlicher Test mit \xc4nderung zum schmei\xdfen.
\\ No newline at end of file
+Das ist \xc3\xb6ffentliecher Test mit \xc3\x84nderung zum schmei\xc3\x9fen.
'
```
As you can see. When I saved this file in sublime I think I chenges the encoding. Look at schmei**fen. So work in progress

**Comment by stoivo** [comment] 2017-02-21 22:36
Dear @deathaxe and @hanoii,
I created a branch [encoding_inlinediff](https://github.com/divmain/GitSavvy/tree/encoding_inlinediff), could you test it so see if it solves the issue?

**Comment by deathaxe** [comment] 2017-02-22 17:42
#### Good news: 
1. No more exceptions are thrown and diff is displayed.
2. Calling inline diff for a staged file works good, too. (git status -> stage file (s) -> inline diff (l) )

#### Bad news: 
Calling inline diff for none staged file with changes, the result is displayed without exceptions, but the content of the working file have wrong encoding.
```
Das ist Ã¶ffentlicher Test mit Ãnderung zum schmeiÃen.
```
It looks like the content of the working file is converted to utf-8 and than displayed using latin-1 or Windows 1252.

Without a look into your code I guess the content of the view is saved to a temporary file, which is then compared against the commited file?

You should use ST's `self.view.encoding()` to get file encoding to use to save the temporary file. This is what GitGutter does. ST is quite smart in detecting encodings and it might be save in most situations to assume its result to be correct for both the local and commited file. One could check and make use of git's encoding setting, too, if explicitly set.

#### Example from GitGutter
```python

    def _get_view_encoding(self):
        """Read view encoding and transform it for use with python.

        This method reads `origin_encoding` used by ConvertToUTF8 plugin and
        goes on with ST's encoding setting if required. The encoding is
        transformed to work with python's `codecs` module.

        Returns:
            string: python compatible view encoding
        """
        encoding = self.view.settings().get('origin_encoding')
        if not encoding:
            encoding = self.view.encoding()
            if encoding == "Undefined":
                encoding = self.view.settings().get('default_encoding')
            begin = encoding.find('(')
            if begin > -1:
                encoding = encoding[begin + 1:-1]
            encoding = encoding.replace('with BOM', '')
            encoding = encoding.replace('Windows', 'cp')
            encoding = encoding.replace('-', '_')
        encoding = encoding.replace(' ', '')
        return encoding


    def update_view_file(self):
        # Read from view buffer
        chars = self.view.size()
        region = sublime.Region(0, chars)
        contents = self.view.substr(region)
        # Try conversion
        try:
            encoding = self._get_view_encoding()
            encoded = contents.encode(encoding)
        except (LookupError, UnicodeError):
            # Fallback to utf8-encoding
            encoded = contents.encode('utf-8')
        # Write the encoded content to file
        if not self._view_temp_file:
            self._view_temp_file = self.tmp_file()
        with open(self._view_temp_file, 'wb') as file:
            if self.view.encoding() == "UTF-8 with BOM":
                file.write(codecs.BOM_UTF8)
            file.write(encoded)

```

**Comment by stoivo** [comment] 2017-02-24 14:08
I have trouble testing this on my mac so, I have a Windows 10 VM I will work on. So I am not done with the issue.

**Comment by stoivo** [comment] 2017-02-24 22:07
@deathaxe, @biz00,  I dont this I can use encoding to current view since I don't read the encoding from the view. Possibly we could open the file then find the encoding and close it again.

I did some more research and found this 
```Everyone I think have spotted the standing issue.

I added couple of loggers to the git command. I looks to me like we are doing some extra work. So here is the flow now.

# Find the sha to the file we openend in inline diff
stdin: None
C:\Program Files\Git\cmd\git.EXE ls-files -s C:\Users\simon\AppData\Roaming\Sublime Text 3\Packages\GitSavvy\gitsavvy-debug\windows1252.txt
dir: None
b'100644 1e08f98f9b68d8c16e06f4041e6a9f0bf377726c 0\twindows1252.txt\n'
utf-8 # decoded output with utf-8


# Read the content of this file on this commit 
# so without our changes
stdin: None
C:\Program Files\Git\cmd\git.EXE show --no-color 1e08f98f9b68d8c16e06f4041e6a9f0bf377726c
dir: None
b'ikke til aa tro\n\nDas ist \xf6ffentlicher Test mit \xc4nderung zum schmei\xdfen.'
utf-8 # decoded output with utf-8 but failed
latin-1 # decode output with latin-1



# Here comes the issue
# We create a sha(fake commit) of the changes we have. 
# The output from the previour command as inout here. 
# https://github.com/divmain/GitSavvy/blob/master/core/git_command.py#L127
# We encode the input as utf-8 allways. So in this fake commit it looks
# like we changed the fileencoding. 
stdin: ikke 0til aa tro

Das ist öffentlicher Test mit Änderung zum schmeißen.
C:\Program Files\Git\cmd\git.EXE hash-object -w --stdin
dir: None
b'c66e2d994f131d9145a3971c4e77d54997d326ab\n'
utf-8


# Here is checks for the diff between index and fake commit. The 
# issue is with the fake commit since it has the utf-8 encoded changes. 
# so the diff is wrong. It looks to me like this command dones the same just 
# git diff --no-color -U0, thou i belive @divmain wrote it like this for 
# a reason. Probably reuse of code. 
stdin None
git diff --no-color -U0 1e08f98f9b68d8c16e06f4041e6a9f0bf377726c c66e2d994f131d9145a3971c4e77d54997d326ab
C:\Program Files\Git\cmd\
git.EXE diff --no-color -U0 1e08f98f9b68d8c16e06f4041e6a9f0bf377726c c66e2d994f131d9145a3971c4e77d54997d326ab
dir: None
b'
diff --git a/1e08f98f9b68d8c16e06f4041e6a9f0bf377726c b/c66e2d994f131d9145a3971c4e77d54997d326ab
index 1e08f98..c66e2d9 100644
--- a/1e08f98f9b68d8c16e06f4041e6a9f0bf377726c
+++ b/c66e2d994f131d9145a3971c4e77d54997d326ab
@@ -1 +1 @@
-ikke til aa tro
+ikke 0til aa tro
@@ -3 +3 @@ ikke til aa tro
-Das ist \xf6ffentlicher Test mit \xc4nderung zum schmei\xdfen.
\\ No newline at end of file
+Das ist \xc3\xb6ffentlicher Test mit \xc3\x84nderung zum schmei\xc3\x9fen.
\\ No newline at end of file
'
utf-8
latin-1
```

So. I think we should make a new argument to git command called stdin_encoding and default it to 'utf-8'.

I don't like wasting time, so should I implement that?

**Comment by divmain** [comment] 2017-02-24 22:41
@stoivo, I think a compromise solution is possible here.  Can #603 be extended to use the [`fallback_encoding`](https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L228) setting?  We could also change this value to be an array instead of a single fallback value.  This way, folks that are working with multiple encodings can determine the order in which they are tried.

I don't think there is going to be a perfect solution to this.  As @stoivo pointed out, we don't always have the file open in a Sublime view before a corresponding Git command is run.  We might be able to pick up hints from Sublime when a view _is_ open but, beyond that, encoding detection is going to be a hard nut to crack.

@stoivo, what do you think?

**Comment by stoivo** [comment] 2017-02-24 23:29
Either way we need to pass how to encode stdino.
We should make it configurable with fallback encofing. 
Tomorrow I will check out how it looks if we open the file, read the encoding then close it.

**Comment by stoivo** [comment] 2017-02-25 08:18
This morning I tested if we could open the file and get the encoding. That did not work as well as I hoped, some of the issues is that it will consume a lot of memory, I can't close the file after it opened and it is not that fast to find the encoding.

**Comment by stoivo** [comment] 2017-02-25 10:41
Please check out https://github.com/divmain/GitSavvy/pull/606

**Comment by stoivo** [comment] 2017-03-04 22:34
@deathaxe, I just want to thank you for reporting this and creating a really great reproduction stepps. This type of issus is simply the best (almost, would be better without issues :) ).
I will close the issue and feel free to reopen.

**Closed by stoivo** 2017-03-04 22:34 UTC
Labels: bug
