### ISSUE TITLE
Error parsing args for custom command

### ISSUE THREAD

**Issue by sentience** [divmain/GitSavvy#232] opened 2015-09-04 00:15 UTC
With the following custom command in User.sublime-commands:

```json
[
  {
    "caption": "git: pull (rebase)",
    "command": "gs_custom",
    "args": {
      "output_to_panel": true,
      "args": ["pull", "--rebase"],
      "start_msg": "Starting pull (rebase)...",
      "complete_msg": "Pull complete."
    }
  }
]
```

I get the following error in the Sublime Text console when attempting to invoke this command:

```
Traceback (most recent call last):
  File "core.commands.custom in /Users/kyank/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 18, in <lambda>
  File "core.commands.custom in /Users/kyank/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 29, in run_async
ValueError: too many values to unpack (expected 2)
```

**Comment by divmain** [comment] 2015-09-09 07:33
Hi @sentience - I'm unable to reproduce on my dev machine.  Can you tell me OS and Sublime version you're using?

**Comment by asfaltboy** [comment] 2015-09-09 09:42
I believe this should be fixed by #228 .

**Comment by divmain** [comment] 2015-09-09 19:13
Oh!  Thanks @asfaltboy.  That change hasn't been included in a release yet, so I'll leave this open until that happens (probably later today).

**Comment by sentience** [comment] 2015-09-10 05:58
:+1:

**Closed** 2015-09-14 17:23 UTC
Labels: bug, question
