### ISSUE TITLE
Status lines cursor issue

### ISSUE THREAD

**Issue by p3lim** [divmain/GitSavvy#419] opened 2016-05-31 17:04 UTC
When the cursor is at the end of the text for a line within any of the categories (staged, unstaged, stashes etc) the hotkeys don't work, and require me to move the cursor one or more characters into the text.

This worked fine before, something must have messed it up.

**Comment by stoivo** [comment] 2016-05-31 17:44
This [commit](https://github.com/divmain/GitSavvy/commit/0b6dd3eac20ba2fb3788e75fca7b866a5b26b2e3) on master was supose to fix it. Can you check if you have this commit.

Maybe duplicate of #414.

**Comment by p3lim** [comment] 2016-05-31 18:25
Probably fixes it, I'm using the latest tag.

**Comment by stoivo** [comment] 2016-05-31 19:49
Ok, than it will be fixed in next release. We are planing to make a new release soon.

**Closed** 2016-05-31 19:50 UTC
Labels: duplicate
