### ISSUE TITLE
Cygwin Git executable path

### ISSUE THREAD

**Issue by sugatov** [divmain/GitSavvy#205] opened 2015-06-22 08:41 UTC
I can't fix it, I had tried to do it many ways. Specifying it through package user config file throwing these:
```
[WinError 267] The directory name is invalid
```
```json
{
    "error": "NotADirectoryError(20, 'The directory name is invalid', None, 267)", 
    "type": "error"
  }, 
  {
    "stdout": null, 
    "stderr": null, 
    "command": [
      "log", 
      "-6000", 
      null, 
      null, 
      "--format=%h%n%H%n%s%n%an%n%at%x00", 
      null, 
      null
    ], 
    "stdin": null, 
    "type": "git"
  }
```
 Even adding ./cygwin/bin to global PATH means nothing for it, while all other shells sees it.
With MinGW-MSYS Git it had worked fine.
```
Your Git binary cannot be found.  If it is installed, add it to your PATH environment variable, or add a `git_path` setting in the `User/GitSavvy.sublime-settings` file.
```

Any advice?
Thanks!

**Comment by divmain** [comment] 2015-06-23 05:07
I'd be glad to help.  Thanks for posting the log.  What paths did you try specifying?

**Comment by sugatov** [comment] 2015-06-23 06:44
The actual path is:
`C:\bin\babun\.babun\cygwin\bin\git.exe`
This was the last value in config file:
```json
{
    "git_path": "C:/bin/babun/.babun/cygwin/bin/git.exe"
}
```
Im tried with backslashes first of course.
Im have an old Git package installed, enabled it and it works fine while `cygwin/bin` added to PATH, but not this package. Other tools like TortoiseGit or shell works fine with it.
I had tryed things like:
 * changing COMSPEC environment variable to `cygwin/bin/bash.exe --login -t` and running Sublime Text from that that shell - does not work;
 * making a shell script `git.cmd` with `set PATH=C:\bin\babun\.babun\cygwin\bin` and `git.exe %*` available system-wide - does not work. This is the way I prefer because it's not exposing all cygwin executables system-wide, but git should work fine finding them.
Need to check this methods with old Git package to be sure Sublime Text can handle it.

**Comment by sugatov** [comment] 2015-06-23 14:33
I had checked [this Git package](https://github.com/kemayo/sublime-text-git) with this method as well:
placing `git.cmd` in a folder available in system-wide PATH, containing:
```bat
@ECHO OFF
@SET PATH=c:\bin\babun\.babun\cygwin\bin
@git.exe %*
```
and it works fine.

**Comment by blaggacao** [comment] 2015-07-19 05:51
Same here, seems to be on following lines
```
        try:
            startupinfo = None
            if os.name == "nt":
                startupinfo = subprocess.STARTUPINFO()
                startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW

            p = subprocess.Popen(command,
                                 stdin=subprocess.PIPE,
                                 stdout=subprocess.PIPE,
                                 stderr=subprocess.PIPE,
                                 cwd=working_dir or self.repo_path,
                                 env=os.environ,
                                 startupinfo=startupinfo)
            stdout, stderr = p.communicate(stdin.encode(encoding="UTF-8") if stdin else None)
            stdout, stderr = stdout.decode(), stderr.decode()

        except Exception as e:
            raise_error(e)
```

It might be that it's not necesarily git related...

**Comment by divmain** [comment] 2015-08-10 07:23
Hey guys, I've been trying to reproduce this in a VM without any luck.  Windows 8.1, Sublime v3095, both Cygwin's Git and Git for Windows, all works for me.  There was some more tweaking that had to happen to get it to work with Cygwin, so I recommend you download the official release from [git-scm.com](https://git-scm.com/download/win), since it also seems that may be a common factor between all of you.

A couple of other thoughts.  Make sure that the permissions for the paths in question are readable by the user under which Sublime is running.  If that doesn't work, I'll try to think of what else we could check...

**Comment by theiviaxx** [comment] 2015-09-07 21:16
im getting the same issue.  I've tried print out the variables in question and can run that exact Popen command without issue.  I tied attaching wing, but the process gets forked or something and wing looses connection immediately.  If i remove the startupinfo stuff, sublime infinitely spams command windows and i am forced to kill sublime.  I'm on build 3083 though on win10.  Could sublime be doing something suspect with subprocess calls?

**Comment by divmain** [comment] 2015-09-09 07:29
I suppose it is possible, but it seems unlikely that they'd modify the default behavior.

@theiviaxx, can you open the console in Sublime and enter the following?
```
import subprocess, os; startupinfo = subprocess.STARTUPINFO(); startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW; print(os.environ); print("--------------"); p = subprocess.Popen(("git", "--version"), stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, env=os.environ, startupinfo=startupinfo); stdout, stderr = p.communicate(); stdout, stderr = stdout.decode(), stderr.decode(); print(stdout); print("--------------"); print(stderr)
```

Copy the results back here for me to take a look at.  Hopefully it'll give us something to go on.

**Comment by theiviaxx** [comment] 2015-09-09 15:12
environ({'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'PSMODULEPATH': 'C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'USERNAME': 'brett', 'APPDATA': 'C:\\Users\\brett\\AppData\\Roaming', 'USERDOMAIN': 'FAMILY-PC', 'LOGONSERVER': '\\\\MicrosoftAccount', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'PUBLIC': 'C:\\Users\\Public', 'COMPUTERNAME': 'FAMILY-PC', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY', 'OS': 'Windows_NT', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'SESSIONNAME': 'Console', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMW6432': 'C:\\Program Files', 'WINGDB_PARENT_PIDS': '1372', 'HOMEPATH': '\\Users\\brett', 'SYSTEMROOT': 'C:\\WINDOWS', 'PROCESSOR_REVISION': '2a07', 'TMP': 'C:\\Users\\brett\\AppData\\Local\\Temp', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'HOMEDRIVE': 'C:', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'VS120COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'TEMP': 'C:\\Users\\brett\\AppData\\Local\\Temp', 'SYSTEMDRIVE': 'C:', 'WINDIR': 'C:\\WINDOWS', 'USERPROFILE': 'C:\\Users\\brett', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 42 Stepping 7, GenuineIntel', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'PATH': 'C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\1.0\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files\\Perforce;C:\\Python27;C:\\Python27\\Scripts;C:\\Program Files\\Git\\bin;C:\\Program Files\\Perforce\\Server', 'LOCALAPPDATA': 'C:\\Users\\brett\\AppData\\Local', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'VS110COMNTOOLS': 'C:\\Program Files (x86)\\Microsoft Visual Studio 11.0\\Common7\\Tools\\', 'NUMBER_OF_PROCESSORS': '4', 'PROCESSOR_LEVEL': '6', 'USERDOMAIN_ROAMINGPROFILE': 'FAMILY-PC', 'FP_NO_HOST_CHECK': 'NO', 'PROGRAMFILES': 'C:\\Program Files', 'PYTHONPATH': 'C:\\Program Files\\Pyblish\\pythonpath;C:\\Program Files\\Pyblish\\lib\\pyblish-x\\integrations\\maya'})
    --------------
    git version 2.5.1.windows.1

    --------------

**Comment by divmain** [comment] 2015-09-09 19:16
Something here doesn't add up.  @theiviaxx, are you seeing the error (described in this ticket) for every Git command attempted?  Or only for specific actions?  The only thing I left out in the above command is the current working directory, `cwd` - and maybe that's the real issue here.  Can you tell me that path of the repo on your machine?  Also, could you create a repo at the root of your drive, and see if GitSavvy works there?

**Comment by theiviaxx** [comment] 2015-09-09 20:34
So the first issue posted here is

    [WinError 267] The directory name is invalid

That is what i'm getting.

Actually, now that i'm typing this, my repo path does have a space in it which would probably cause problems when using Popen with a string.  I'll try using it as a tuple.  If that works i'll make a pull request.  Sorry for the run around

**Comment by theiviaxx** [comment] 2015-09-10 06:17
Ok so upon further inspection this was user error, but something that can be caught.  I had copied the repo to a different drive and when gitsavvy went looking for the repo_path, it found it in the sublime-workspace file, however that path was no longer valid. see pull request #233

**Comment by divmain** [comment] 2015-09-10 09:43
@sugatov @blaggacao, does @theiviaxx's summary of the cause seem to fit your respective situations?

**Comment by blaggacao** [comment] 2015-09-10 15:10
I honestly don't remember the issue.

**Comment by divmain** [comment] 2015-09-10 19:39
Fair enough.  I'm going to close this out.  Please let me know if this rears its head again.

**Closed by divmain** 2015-09-10 19:39 UTC
Labels: os-specific, question

**Comment by blaggacao** [comment] 2016-01-06 01:45
It rears it's head again, I get a cygwin path...

```
{
    "stderr": "", 
    "stdout": "/cygdrive/b/odoo/addons/account_account_detail\n", 
    "type": "git", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ], 
    "stdin": null
  }, 
```

That's very weird, because my Paths are more or less clean, and Sublime is not started from cygwin or anything, any ideas where to look for?
![image](https://cloud.githubusercontent.com/assets/7548295/12132767/1b74dcba-b3ed-11e5-9814-87bea535c340.png)

![image](https://cloud.githubusercontent.com/assets/7548295/12132774/2abc8a24-b3ed-11e5-8664-1b5666f505ce.png)

**Comment by blaggacao** [comment] 2016-01-06 01:53
Changing user settings to:
```
{
	"git_path": {
		"default": "",
		"windows": "C:/Program Files/Git/cmd/git.exe"
	},
}
```
Yields an OK:
```
  {
    "stderr": "", 
    "stdout": "## develop...origin/develop\n", 
    "type": "git", 
    "stdin": null, 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ]
  }, 
```
However, I can't explain this...

**Comment by divmain** [comment] 2016-01-07 05:28
Hi @blaggacao, if I'm understanding you correctly, this is unsurprising.  If you use the Cygwin git command, it is designed to function in the emulated Unix-like layer.  Because of that, it is going to report paths as they function within Cygwin (`/cygdrive/b/odoo/...`).  If you use the Windows Git binary, it is designed to function using Windows paths, which is why it works as expected.

**Comment by blaggacao** [comment] 2016-01-10 06:32
@divmain Thanks, Dale! The bit I'm wondering about is, that I was not knowingly using the cygwin git (I just left the git path undefined), and sublime is not being called from cygwin environment. Furthermore the cygwin git is not in the windows paths.

**Comment by divmain** [comment] 2016-01-10 08:31
Cygwin `git` not being in the Windows path is very peculiar.  I think I'll roll this into #340.  Ideally the diagnostics command would reveal some of the underlying config that leads to the situation you were in prior to changing your `git_path` value.
