### ISSUE TITLE
Permission denied (publickey) on push

### ISSUE THREAD

**Issue by ihorvorotnov** [divmain/GitSavvy#243] opened 2015-09-25 14:09 UTC
Everything is working properly except the `git push` commands (all of them). I'm getting this error in console:

```
`C:/Program Files (x86)/Git/cmd/git.exe push origin development:development` failed with following output:

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

- Git path is correct and repo (and branch) exists
- `git push` is working fine from Git Bash, SourceTree etc
- The repo is on BitBucket.org (private repo)
- Windows 10 x64, Git 1.9.5 (latest available for Windows), Sublime Text 3 Build 3083, GitSavvy most recent from this GitHub repo

My guess is GitSavvy can't use publickey authentication out of the box, it will work with https:// urls, not SSH (git@...). Couldn't find in Docs/Help if I can add a path to private SSH key somewhere in my user settings file. Is it a limitation? Any chance to make it work?

**Comment by divmain** [comment] 2015-09-25 20:31
GitSavvy should use the same operating environment for `git` commands as that it was started with.  There is no known limitation wrt using ssh remotes - just confirmed this myself using my Windows 10 VM with the same version of Sublime.  Is it possible that Sublime is being started under a different user account?  That would explain why your terminal has the correct environment values and Sublime/GitSavvy does not.

**Comment by divmain** [comment] 2015-10-07 09:36
Going to close this, but feel free to re-open if you're unable to resolve the issue.  Alternately, feel free to reach out on [Gitter](https://gitter.im/divmain/GitSavvy).

**Comment by ihorvorotnov** [comment] 2015-10-07 10:45
Sorry, was pretty busy, had no time to handle it. However, there's Git 2.6.1 for Windows finally available (previous version was 1.9.*), and it's available in x64 as well. Removed old Git, installed new one, configured SSH keys [like this](https://gist.github.com/ihorvorotnov/788ea8226e17b6747ed9) and now everything works fine. Including default Git path (I had another issue about it), which is exactly `C:/Program Files/Git` for x64 version.

**Comment by stoivo** [comment] 2015-10-07 12:02
Good it work to by updating Git

**Comment by grubernaut** [comment] 2016-08-24 17:40
I'm getting this issue on macOS Sierra, ST3 build 3114, and GitSavvy v2.12.1

I can pull/push with git correctly when I start `subl` from my terminal. However, starting sublime outside terminal causes an error. 

Running some debug commands, finds that ST when launched outside of a terminal session isn't aware of the currently running `ssh-agent`, and therefore can't use my ssh-key to authenticate to github. 

From the ST3 Console, the only `SSH` environment variable I show is `SSH_AUTH_SOCK`. However, in my terminal I'm actually attached to the running ssh agent, as I have `SSH_AGENT_PID` in my environment variables, hence why it's working when I launch from my terminal. 

I'm not sure if this is a change that's occurring with macOS Sierra, or python being unable to correctly bind to the `SSH_AUTH_SOCK`, or start an `ssh-agent`.

**Comment by stoivo** [comment] 2016-08-24 19:31
Okey, let me see if I can help you. It is quite hard to tell what causes this issue. Mostly because I can't reproduce it on my mac(El Capitan).

I think it has something with your PATH and which Git binaries you are using. Can you open the Sublime Console (`View` -> `Show Console`) and run these one?
```python
import os; os.environ.get('PATH')
import shutil; shutil.which("git")
```
And in your terminal
```bash
echo $PATH
which git
```

And dump the output here. You might want to remove name from the output before you post it here.

**Comment by grubernaut** [comment] 2016-08-24 19:40
ST3:
```
>>> import shutil; shutil.which('git')
'/usr/bin/git'
```

Terminal:
```
$ which git
/usr/local/bin/git
```

Think that solved it thanks :)

**Comment by stoivo** [comment] 2016-08-24 20:46
Nice, either try to add it to GitSavvy.sublime-settings
https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L8-L23
or use something like 
https://github.com/int3h/SublimeFixMacPath

**Comment by stoivo** [comment] 2016-08-24 20:47
Glad to help. Feel free to reopen if there is any questions.

**Closed by stoivo** 2016-08-24 20:47 UTC
Labels: archive, question

**Comment by afcuttin** [comment] 2019-06-21 12:39
Indeed this happens also under linux (Ubuntu 18.04 lts with ST build 3207, git savvy 2.18.0)

> I'm getting this issue on macOS Sierra, ST3 build 3114, and GitSavvy v2.12.1
> 
> I can pull/push with git correctly when I start `subl` from my terminal. However, starting sublime outside terminal causes an error.
> 
> Running some debug commands, finds that ST when launched outside of a terminal session isn't aware of the currently running `ssh-agent`, and therefore can't use my ssh-key to authenticate to github.
> 
> From the ST3 Console, the only `SSH` environment variable I show is `SSH_AUTH_SOCK`. However, in my terminal I'm actually attached to the running ssh agent, as I have `SSH_AGENT_PID` in my environment variables, hence why it's working when I launch from my terminal.
>

**Comment by afcuttin** [comment] 2019-06-21 12:45
> Nice, either try to add it to GitSavvy.sublime-settings
> https://github.com/divmain/GitSavvy/blob/master/GitSavvy.sublime-settings#L8-L23

adding
```
{
    "git_path": "/usr/bin/git",
}
```
in `GitSavvy.sublime-settings` solves my problem

**Comment by IPWright83** [comment] 2020-06-30 14:49
I seem to be getting this too at the moment and I'm not sure why. I re-install the package yesterday which must be when it broke.

`which git` > `/usr/bin/git`

These are my settings:

```
// Settings in here override those in "GitSavvy/GitSavvy.sublime-settings",

{
    "git_path": "/usr/bin/git",
    "global_flags": {
        "commit": ["--cleanup=strip"]
    }
}

```

Am I missing something?
