### ISSUE TITLE
Github Integration broken?

### ISSUE THREAD

**Issue by wldcordeiro** [divmain/GitSavvy#139] opened 2015-03-25 18:58 UTC
I noticed that I'm getting errors for issue and contributor completion regarding my credentials. I've updated my preferences to include the API token but can't get it to run.

**Comment by divmain** [comment] 2015-03-25 19:07
Hmm, it is working for me for both GitHub.com and GH Enterprise.  Can you paste the exact error output @wldcordeiro?

**Comment by wldcordeiro** [comment] 2015-03-25 20:03
```Traceback (most recent call last):
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/commands/commit.py", line 76, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async())
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/commands/commit.py", line 82, in run_async
    contributors = github.get_contributors(remote)
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/github.py", line 99, in query_github
    raise FailedGithubRequest(response.payload)
GitSavvy.github.github.FailedGithubRequest: {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}
Traceback (most recent call last):
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/commands/commit.py", line 76, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async())
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/commands/commit.py", line 82, in run_async
    contributors = github.get_contributors(remote)
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/github.py", line 99, in query_github
    raise FailedGithubRequest(response.payload)
GitSavvy.github.github.FailedGithubRequest: {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}```

**Comment by divmain** [comment] 2015-03-25 20:06
Do you have an entry in your `GitSavvy.sublime-settings` that looks like this?
```
{
    // ...
    "api_tokens": {
        "github.com": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    }
}

```

The token itself should be 40-characters.

**Comment by wldcordeiro** [comment] 2015-03-25 20:08
```json
{
  "api_tokens": {
      "github.com": "apikeyhere"
  },
  "git_graph_args": [
      "log",
      "--oneline",
      "--decorate",
      "--all",
      "--pretty=format:'%C(yellow)%h%Cred%d\\ %Creset%s%Cblue\\ [Author: %an, Committer: %cn]'"
  ]
}
```

**Comment by wldcordeiro** [comment] 2015-03-25 20:10
Upon further inspection I'm getting these errors as well.

```
Traceback (most recent call last):
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/commands/commit.py", line 35, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async(nondefault_repo))
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/commands/commit.py", line 51, in run_async
    issues = github.get_issues(remote)
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/github.py", line 99, in query_github
    raise FailedGithubRequest(response.payload)
GitSavvy.github.github.FailedGithubRequest: {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3'}
Traceback (most recent call last):
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/commands/commit.py", line 76, in <lambda>
    sublime.set_timeout_async(lambda: self.run_async())
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/commands/commit.py", line 82, in run_async
    contributors = github.get_contributors(remote)
  File "/home/wldcordeiro/.config/sublime-text-3/Packages/GitSavvy/github/github.py", line 99, in query_github
    raise FailedGithubRequest(response.payload)
GitSavvy.github.github.FailedGithubRequest: {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3'}
```

**Comment by divmain** [comment] 2015-03-25 20:11
@wldcordeiro, go [here](https://github.com/settings/tokens/new), enter "GitSavvy" for the token description, and click `Generate token`.  On the next page, you should see a 40-character token highlighted in green.  Replace `apikeyhere` in your settings file with the 40-character token, save, and restart Sublime.

**Comment by wldcordeiro** [comment] 2015-03-25 20:17
I have the actual token there. I just didn't want to put my real token.

**Comment by divmain** [comment] 2015-03-25 20:41
Ah, sorry.  The first error definitely looks like a valid API response based on invalid credentials.  In the terminal, try:

```
curl -X GET --user YOUR_API_TOKEN:x-oauth-basic https://api.github.com/repos/divmain/GitSavvy/issues
```

Make sure the token is copied verbatim from your settings file.  If you get a "Bad credentials" message, then your token is invalid somehow.  If you get back issues JSON, let me know!

**Comment by wldcordeiro** [comment] 2015-03-25 20:52
I got the JSON dump of the issues page.

**Comment by divmain** [comment] 2015-03-25 21:14
Weird!  Alright, I'll look into places where you can place debug statements, since I can't reproduce locally.

**Comment by yyyc514** [comment] 2015-03-25 23:30
divmain:  I ran into an issue with issues.  The before_issue string includes the # in my testing, but the regex does not include "#"... so tabbing seems to do nothing (or does th wrong thing, I forget).  Maybe related?

**Comment by yyyc514** [comment] 2015-03-27 06:47
Can you try #145

**Comment by mcbrwr** [comment] 2015-07-02 04:53
I seem to get the same kind of error, but with a slightly different message.
When I commit and want to reference a github issue with just `#` it's not showing anything and produces this error:

````
Traceback (most recent call last):
  File "github.commands.commit in /Users/matthijs/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 36, in <lambda>
  File "github.commands.commit in /Users/matthijs/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 51, in run_async
  File "github.github in /Users/matthijs/Library/Application Support/Sublime Text 3/Installed Packages/GitSavvy.sublime-package", line 99, in query_github
GitSavvy.github.github.FailedGithubRequest: {'documentation_url': 'https://developer.github.com/v3', 'message': 'Not Found'}
````

And when I reference the issue with full repo name it is working. When using "github: open file on remote" it works fine, so the repository can be found.

**Comment by divmain** [comment] 2015-07-02 06:07
Hi @mcbrwr - could you do the following:

1. Open the commit view.
2. `GitSavvy: start logging`
3. Enter `#` character and press `TAB`.
4. `GitSavvy: stop logging`
5. `GitSavvy: view recorded log`
6. Paste the output here.

Hopefully that will provide more insight into what is broken.  Thanks!

**Comment by mcbrwr** [comment] 2015-07-02 06:54
here you go:

````
[
  {
    "stdin": null, 
    "stderr": "", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "type": "git", 
    "stdout": "## master...origin/master\nA  assets/_source/less/inc/sitenav-logic.less\n"
  }, 
  {
    "stdin": null, 
    "stderr": "", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "type": "git", 
    "stdout": "## master...origin/master\nA  assets/_source/less/inc/sitenav-logic.less\n"
  }, 
  {
    "stdin": null, 
    "stderr": "", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "type": "git", 
    "stdout": "## master...origin/master\nA  assets/_source/less/inc/sitenav-logic.less\n"
  }, 
  {
    "stdin": null, 
    "stderr": "", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "type": "git", 
    "stdout": "## master...origin/master\nA  assets/_source/less/inc/sitenav-logic.less\n"
  }, 
  {
    "stdin": null, 
    "stderr": "", 
    "command": [
      "remote", 
      "-v"
    ], 
    "type": "git", 
    "stdout": "dev\twww-data@artandflywork.com:/storage/websites/dev.artandflywork.com/matthijs/httpdocs (fetch)\ndev\twww-data@artandflywork.com:/storage/websites/dev.artandflywork.com/matthijs/httpdocs (push)\norigin\tgit@github.com:mcbrwr/matthijsbrouwer_nl.git (fetch)\norigin\tgit@github.com:mcbrwr/matthijsbrouwer_nl.git (push)\n"
  }, 
  {
    "stdin": null, 
    "stderr": "", 
    "command": [
      "config", 
      "--local", 
      "--get", 
      "GitSavvy.ghRemote"
    ], 
    "type": "git", 
    "stdout": "origin\n"
  }, 
  {
    "stdin": null, 
    "stderr": "", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "type": "git", 
    "stdout": "## master...origin/master\nA  assets/_source/less/inc/sitenav-logic.less\n"
  }, 
  {
    "stdin": null, 
    "stderr": "", 
    "command": [
      "status", 
      "-b", 
      "--porcelain"
    ], 
    "type": "git", 
    "stdout": "## master...origin/master\nA  assets/_source/less/inc/sitenav-logic.less\n"
  }
]
````

**Comment by divmain** [comment] 2015-07-16 08:47
@mcbrwr, within the context of this repo, what does typing `git remote -vv` in the terminal return?  I'm stymied why this wouldn't be working, unless there's a regex somewhere that's failing to parse the URL of your git remote.

**Comment by mcbrwr** [comment] 2015-07-16 14:21
thanks for looking into it.

````
dev	www-data@artandflywork.com:/storage/websites/dev.artandflywork.com/matthijs/httpdocs (fetch)
dev	www-data@artandflywork.com:/storage/websites/dev.artandflywork.com/matthijs/httpdocs (push)
origin	git@github.com:mcbrwr/matthijsbrouwer_nl.git (fetch)
origin	git@github.com:mcbrwr/matthijsbrouwer_nl.git (push)
````

Maybe it doesn't handle the secondary repo well?

**Comment by divmain** [comment] 2015-08-10 07:35
@mcbrwr, this should be fixed now in master.

@wldcordeiro, I'm not sure what steps to take next to debug this for you.  It seems unrelated to @mcbrwr's issue.  I'll be adding deeper logging for situations like this down the line, but not sure how to proceed with this until then.

**Closed** 2016-01-27 22:15 UTC
Labels: bug, investigate

**Comment by TheRealJoeLinux** [comment] 2017-06-23 13:07
Seems this has been dropped, but I'm getting the same issue with GitSavvy (just installed it today). I added the GH token, attempted the above-suggested command on the command line and got the JSON back, and I _also_ have multiple remotes. I did the logging suggestion:

1. Commit view
2. GitSavvy: enable logging
3. Entered Insert mode (I'm on Vintageous), typed `#` and hit Tab
4. GitSavvy: disable logging
5. GitSavvy: view recorded log

This is what I got:
```
[
  {
    "stdin": null, 
    "stderr": "", 
    "type": "git", 
    "stdout": "/home/joelinux/Projects/verify-api\n", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ]
  }, 
  {
    "stdin": null, 
    "stderr": "", 
    "type": "git", 
    "stdout": "/home/joelinux/Projects/verify-api\n", 
    "command": [
      "rev-parse", 
      "--show-toplevel"
    ]
  }
]
```

**Comment by stoivo** [comment] 2017-06-23 13:28
Do you have any messages in the console?
and can you try to follow the steps in https://github.com/divmain/GitSavvy/issues/139#issuecomment-86207570 ?

**Comment by TheRealJoeLinux** [comment] 2017-06-23 13:36
@stoivo Yep, I did that. I got back the issues JSON successfully, and it looks right. How can I check for messages in the console? I tried opening sublime via the cli, and seeing if it spit anything out (it didn't). Is there another place I can look? I'm on Ubuntu 16.04.

**Comment by stoivo** [comment] 2017-06-23 14:16
oh, ctrl+`. or < `View` -> `Show console`

**Comment by TheRealJoeLinux** [comment] 2017-06-23 15:28
You know what... false alarm. It works, the `#` just can't be at the beginning of a line (presumably treated as a comment).

**Comment by stoivo** [comment] 2017-06-23 16:02
Good to hear!
