### ISSUE TITLE
Provide ability to delete, add, and open untracked files in `git: status` view

### ISSUE THREAD

**Issue by ethanbustad** [divmain/GitSavvy#17] opened 2015-02-12 20:38 UTC

**Comment by divmain** [comment] 2015-02-12 20:55
This should be working.  Can you open the console (`CTRL-~`) and see if it shows any errors there?  I'll also test in my Windows VM.

**Comment by divmain** [comment] 2015-02-12 21:04
I confirmed the following under Windows 7 32-bit and Sublime Text 3, dev build 3069:

- Highlighting file and hitting `s` in stage view will add untracked file.
- Highlighting file and hitting `o` in stage view does open an untracked file.
- `d` will not discard, but I suppose I could just have it delete the file altogether.  One possible issue with that is mistakenly hitting `d` when the wrong thing is highlighted, and since it isn't staged or committed you lose your work.  Maybe it could prompt and confirm.

**Comment by ethanbustad** [comment] 2015-02-12 21:08
Yeah, you're right. I first noticed the inability to delete the file, but when I went to test that the other actions worked (when I was making the ticket) it didn't work. But now it does. Most of the time..... I just had to hit 'u' a few times before it ended up unstaging my untracked file... but it looks like it's probably fine? Not sure why it would only work inconsistently.

**Comment by divmain** [comment] 2015-02-12 21:29
Yeah that's very weird.  If you notice it failing, open the console to see if there are any exceptions.  It is also possible that Git is taking a little extra time under the hood on some executions, which would explain a delay if not an outright failure.

**Comment by divmain** [comment] 2015-02-12 21:31
Oh, and there is a bug where if the cursor is at the end of the line where a filename is listed, it doesn't perform the action correctly.  I forgot about that - I'll file a bug.

**Comment by divmain** [comment] 2015-02-13 07:20
If you notice it again, and the errant behavior is not covered by #18, please re-open.

**Closed by divmain** 2015-02-13 07:20 UTC
Labels: bug, windows
