### ISSUE TITLE
Syntax highlight for show_word_diff

### ISSUE THREAD

**Issue by NicoSantangelo** [divmain/GitSavvy#295] opened 2015-11-28 23:12 UTC
Hello! I couldn't find an issue for this so I'm not completely sure if I'm missing something.

When seeing diffs for a file everything works fine:

![image](https://cloud.githubusercontent.com/assets/692077/11454469/fb60dc66-960b-11e5-83d4-ffeea39b1cb8.png)

But when I toggle to `word_diff` using `w`:

![image](https://cloud.githubusercontent.com/assets/692077/11454472/0b5c9920-960c-11e5-875b-0d20e8d9ee0f.png)

The color is missing.

I think this happens because the Syntax Highlight for the diff view does not support `[-del:-]` and `{+add:+}` as adds/dels.
If this is the case and this is a desirable, I can give it a try!

Thanks!

**Comment by stoivo** [comment] 2015-11-29 22:09
Hey,

You are right. This is not only your sublime. When I created world-diff I did not add colors, since we don't use our own diff syntax but sublimes. and this one does not  support ` [-del:-]` and `{+add:+}` as adds/dels.

So either you should create a new whole diff syntax which is a lot of work and hard to hit all cornycases OR make sublime diff syntax better(report a issue and follow up) which  I think is better but harder to get done.

Maybe we should write something about this on our docs?

**Comment by NicoSantangelo** [comment] 2015-11-30 13:54
Aw that's a shame. 
I'm going to file an issue on [DefaultPackages](https://github.com/SublimeTextIssues/DefaultPackages/issues) but it seems that the development is a bit stalled so I'll give the syntax a go.

I think updating the docs it's a good idea to avoid confusion but, if this is the first time this issue has been filed, maybe it's not necessary?

Thanks :)

**Comment by stoivo** [comment] 2015-12-01 07:13
This is first issue. I don't think we need to write anything at least not if you manage to fix it.

**Comment by divmain** [comment] 2015-12-01 10:07
@NicoSantangelo, please feel free to take a go at the syntax file!  @stoivo and I discussed this at the time the feature was introduced, and I haven't had time to revisit and add this myself.

**Comment by NicoSantangelo** [comment] 2015-12-01 23:03
Hey! I have a working local version which looks like this:

![image](https://cloud.githubusercontent.com/assets/692077/11516919/378f0928-9865-11e5-9479-809f49c4f99a.png)

but I have a little question regarding the implementation.

I can set the syntax only when the user chooses `word-diff` or we can use this syntax for the hole diff command (changing [line 38 of diff.py](https://github.com/divmain/GitSavvy/blob/bf788bdb51215157dfa0c597ed159f51c17869c7/core/commands/diff.py#L38)) because the syntax highlight I wrote includes `source.diff` so it should be the same.
Which one do you prefer?

**Comment by stoivo** [comment] 2015-12-03 16:50
I prefer it we   always use the one you created if it works all the time.

**Comment by divmain** [comment] 2015-12-03 19:00
If default-mode behavior is unchanged, using it for all GitSavvy diffs seems reasonable to me.  The only potential downside is if changes are made to the diff syntax file in the default Sublime package, but that seems like a very slight downside.

**Comment by NicoSantangelo** [comment] 2015-12-04 14:13
It shouldn't be a problem because I'm including the default diff syntax, so if it changes it should be reflected on Git Savvy.

I'll make the PR today :), thanks for the feedback

**Comment by divmain** [comment] 2015-12-04 19:54
Excellent :+1:

**Comment by whophil** [comment] 2016-02-20 03:40
Is this supposed to be working? I'm on GitSavvy 2.9.1 and Ubuntu 14.04. The normal diff works fine, but the `--word-diff` version appears in all yellow.

![screenshot from 2016-02-19 19 31 14](https://cloud.githubusercontent.com/assets/2186528/13194281/803c251a-d740-11e5-948d-2167cf49d67d.png)
![screenshot from 2016-02-19 19 31 19](https://cloud.githubusercontent.com/assets/2186528/13194283/883c3de0-d740-11e5-94d5-c6425210fd89.png)

**Comment by stoivo** [comment] 2016-02-20 10:06
I can confirm the bug. So it is a bug :smile: ![imgage](http://puu.sh/neHKI/1c1ff62fcf.png)

The problem is that the line beginnings on `!`
Thanks to reporting this.

This will have to be solved in #349 too.

**Comment by stoivo** [comment] 2016-02-20 11:55
BTW, This is not an issue in GitSavvys code or syntax files. This is an issue in for [sublimehq/Packages](https://github.com/sublimehq/Packages). I will take it from here. I addressed it to this: [Diff/Diff.sublime-syntax#L58-L61](https://github.com/sublimehq/Packages/blob/master/Diff/Diff.sublime-syntax#L58-L61).

**Comment by whophil** [comment] 2016-02-21 01:19
Thanks for looking into this @stoivo.

Is it possible to remove a rule from the default `Diff.sublime-syntax file` using a patch? If not, it may be worth considering to have a separate `.sublime-syntax` file for GitSavvy Diff, instead of patching the default `Diff.sublime-syntax` as is done now. The original syntax rule for matching exclamation-prefixed lines only applies to context-formatted diff output (`diff -c`), which `git diff` can not produce natively anyway - it is this rule gives problems for the !-prefixed lines here. There may also be other subtle differences between `diff` and `git diff` outputs which I am not aware of.

**Comment by stoivo** [comment] 2016-03-03 12:11
The issue is fix but I will wait with closing this until it get merged into master and released.

**Comment by divmain** [comment] 2016-03-03 20:05
@stoivo, the issue will be automatically closed when the commit is merged into master, because you added `Fixes #295` :)

**Comment by stoivo** [comment] 2016-03-03 21:36
I forgot that. And you are totally correct.

**Closed** 2016-03-29 18:16 UTC
Labels: archive, enhancement, ux
